In [96]:
import pandas as pd
df = pd.read_csv('fte.csv')
print(df.head(5))

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971
3  2017-01-05    75.705     75.805     73.312      73.511    19547
4  2017-01-09    73.790     75.197     72.414      72.813    14825

In [14]:
print(df.tail())

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
660  2019-08-27     25.00      25.20       24.5       24.95     8037
661  2019-08-28     25.20      25.20       24.3       24.30     1345
662  2019-08-29     25.00      25.00       24.2       25.00      977
663  2019-08-30     24.95      25.00       24.4       25.00     3335
664  2019-09-02     25.00      25.15       24.7       25.00      589

In [15]:
len(df)

665

In [20]:
df_xls = pd.read_excel('fte.xls')
df.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [23]:
df_xlsx = pd.read_excel('fte.xlsx')
df.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [25]:
df_txt = pd.read_csv('fte.txt')
df_txt.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [31]:
print(df.columns)

Index(['Data', 'Otwarcie', 'Najwyzszy', 'Najnizszy', 'Zamkniecie', 'Wolumen'], dtype='object')

In [43]:
print(df[['Data', 'Otwarcie', 'Zamkniecie']].head(3))

         Data  Otwarcie  Zamkniecie
0  2017-01-02    74.858      77.102
1  2017-01-03    77.800      76.503
2  2017-01-04    76.603      75.606

In [42]:
print(df.Data.head(3))

0    2017-01-02
1    2017-01-03
2    2017-01-04
Name: Data, dtype: object

In [52]:
print(df.iloc[22:33])

          Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
22  2017-02-02    82.687     82.737     81.540      82.079     2421
23  2017-02-03    82.987     82.987     80.992      81.291     3901
24  2017-02-06    81.750     83.475     81.291      81.291     3566
25  2017-02-07    81.491     81.491     78.957      79.845     5071
26  2017-02-08    79.765     81.281     78.897      81.281     4911
27  2017-02-09    81.281     84.952     80.124      83.785     8658
28  2017-02-10    83.785     84.283     83.386      83.685     1321
29  2017-02-13    83.785     83.785     82.777      82.787     1546
30  2017-02-14    82.787     82.787     81.341      81.780     2057
31  2017-02-15    82.039     82.189     81.301      81.870     2672
32  2017-02-16    82.877     82.987     79.725      81.780    10659

In [59]:
print(df.iloc[22:25,3:5])

    Najnizszy  Zamkniecie
22     81.540      82.079
23     80.992      81.291
24     81.291      81.291

#### DataFrame.iterrows

In [84]:
for a, b in df.iterrows():
    print(a, b[['Data', 'Otwarcie', 'Zamkniecie', 'Wolumen']])

0 Data          2017-01-02
Otwarcie          74.858
Zamkniecie        77.102
Wolumen            14020
Name: 0, dtype: object
1 Data          2017-01-03
Otwarcie            77.8
Zamkniecie        76.503
Wolumen             2055
Name: 1, dtype: object
2 Data          2017-01-04
Otwarcie          76.603
Zamkniecie        75.606
Wolumen             2971
Name: 2, dtype: object
3 Data          2017-01-05
Otwarcie          75.705
Zamkniecie        73.511
Wolumen            19547
Name: 3, dtype: object
4 Data          2017-01-09
Otwarcie           73.79
Zamkniecie        72.813
Wolumen            14825
Name: 4, dtype: object
5 Data          2017-01-10
Otwarcie          72.813
Zamkniecie        73.411
Wolumen            93285
Name: 5, dtype: object
6 Data          2017-01-11
Otwarcie          73.411
Zamkniecie        74.618
Wolumen             3876
Name: 6, dtype: object
7 Data          2017-01-12
Otwarcie          74.618
Zamkniecie        74.199
Wolumen              927
Name: 7, dtype: object
8 Data          2017-01-13
Otwarcie           73.81
Zamkniecie         74.07
Wolumen            20616
Name: 8, dtype: object
9 Data          2017-01-16
Otwarcie           74.07
Zamkniecie        74.608
Wolumen             2568
Name: 9, dtype: object
10 Data          2017-01-17
Otwarcie          74.558
Zamkniecie        75.486
Wolumen             2552
Name: 10, dtype: object
11 Data          2017-01-18
Otwarcie          75.606
Zamkniecie        76.473
Wolumen             7508
Name: 11, dtype: object
12 Data          2017-01-19
Otwarcie          76.404
Zamkniecie        75.805
Wolumen            17281
Name: 12, dtype: object
13 Data          2017-01-20
Otwarcie          76.104
Zamkniecie        76.533
Wolumen            12876
Name: 13, dtype: object
14 Data          2017-01-23
Otwarcie          77.202
Zamkniecie        76.902
Wolumen             5484
Name: 14, dtype: object
15 Data          2017-01-24
Otwarcie          76.603
Zamkniecie        76.703
Wolumen            13639
Name: 15, dtype: object
16 Data          2017-01-25
Otwarcie          78.997
Zamkniecie        80.992
Wolumen            20593
Name: 16, dtype: object
17 Data          2017-01-26
Otwarcie          84.583
Zamkniecie        83.785
Wolumen            17243
Name: 17, dtype: object
18 Data          2017-01-27
Otwarcie          81.889
Zamkniecie        81.371
Wolumen             5751
Name: 18, dtype: object
19 Data          2017-01-30
Otwarcie          81.281
Zamkniecie        82.787
Wolumen             4636
Name: 19, dtype: object
20 Data          2017-01-31
Otwarcie          82.787
Zamkniecie        82.787
Wolumen            11637
Name: 20, dtype: object
21 Data          2017-02-01
Otwarcie          82.797
Zamkniecie        82.777
Wolumen             7932
Name: 21, dtype: object
22 Data          2017-02-02
Otwarcie          82.687
Zamkniecie        82.079
Wolumen             2421
Name: 22, dtype: object
23 Data          2017-02-03
Otwarcie          82.987
Zamkniecie        81.291
Wolumen             3901
Name: 23, dtype: object
24 Data          2017-02-06
Otwarcie           81.75
Zamkniecie        81.291
Wolumen             3566
Name: 24, dtype: object
25 Data          2017-02-07
Otwarcie          81.491
Zamkniecie        79.845
Wolumen             5071
Name: 25, dtype: object
26 Data          2017-02-08
Otwarcie          79.765
Zamkniecie        81.281
Wolumen             4911
Name: 26, dtype: object
27 Data          2017-02-09
Otwarcie          81.281
Zamkniecie        83.785
Wolumen             8658
Name: 27, dtype: object
28 Data          2017-02-10
Otwarcie          83.785
Zamkniecie        83.685
Wolumen             1321
Name: 28, dtype: object
29 Data          2017-02-13
Otwarcie          83.785
Zamkniecie        82.787
Wolumen             1546
Name: 29, dtype: object
30 Data          2017-02-14
Otwarcie          82.787
Zamkniecie         81.78
Wolumen             2057
Name: 30, dtype: object
31 Data          2017-02-15
Otwarcie          82.039
Zamkniecie         81.87
Wolumen             2672
Name: 31, dtype: object
32 Data          2017-02-16
Otwarcie          82.877
Zamkniecie         81.78
Wolumen            10659
Name: 32, dtype: object
33 Data          2017-02-17
Otwarcie          82.388
Zamkniecie        80.792
Wolumen             4819
Name: 33, dtype: object
34 Data          2017-02-20
Otwarcie          81.092
Zamkniecie        80.982
Wolumen            18356
Name: 34, dtype: object
35 Data          2017-02-21
Otwarcie          80.792
Zamkniecie        80.992
Wolumen             8408
Name: 35, dtype: object
36 Data          2017-02-22
Otwarcie          80.982
Zamkniecie        82.288
Wolumen             2884
Name: 36, dtype: object
37 Data          2017-02-23
Otwarcie          83.785
Zamkniecie        83.685
Wolumen             2255
Name: 37, dtype: object
38 Data          2017-02-24
Otwarcie          83.775
Zamkniecie        84.383
Wolumen             3470
Name: 38, dtype: object
39 Data          2017-02-27
Otwarcie          83.685
Zamkniecie        83.066
Wolumen             4584
Name: 39, dtype: object
40 Data          2017-02-28
Otwarcie          82.288
Zamkniecie        83.785
Wolumen             3595
Name: 40, dtype: object
41 Data          2017-03-01
Otwarcie          83.685
Zamkniecie        83.685
Wolumen             5695
Name: 41, dtype: object
42 Data          2017-03-02
Otwarcie          83.695
Zamkniecie        85.171
Wolumen             6031
Name: 42, dtype: object
43 Data          2017-03-03
Otwarcie          84.383
Zamkniecie        85.231
Wolumen             2725
Name: 43, dtype: object
44 Data          2017-03-06
Otwarcie          85.271
Zamkniecie        84.423
Wolumen              707
Name: 44, dtype: object
45 Data          2017-03-07
Otwarcie          84.263
Zamkniecie        82.787
Wolumen            15403
Name: 45, dtype: object
46 Data          2017-03-08
Otwarcie          82.787
Zamkniecie        81.181
Wolumen            14775
Name: 46, dtype: object
47 Data          2017-03-09
Otwarcie          81.062
Zamkniecie        78.827
Wolumen             6027
Name: 47, dtype: object
48 Data          2017-03-10
Otwarcie          78.847
Zamkniecie        81.151
Wolumen             5952
Name: 48, dtype: object
49 Data          2017-03-13
Otwarcie          83.775
Zamkniecie        83.585
Wolumen            20527
Name: 49, dtype: object
50 Data          2017-03-14
Otwarcie          84.692
Zamkniecie        83.705
Wolumen            21007
Name: 50, dtype: object
51 Data          2017-03-15
Otwarcie          83.705
Zamkniecie        83.276
Wolumen            21202
Name: 51, dtype: object
52 Data          2017-03-16
Otwarcie          83.286
Zamkniecie        83.286
Wolumen             3212
Name: 52, dtype: object
53 Data          2017-03-17
Otwarcie          83.286
Zamkniecie        83.206
Wolumen             9920
Name: 53, dtype: object
54 Data          2017-03-20
Otwarcie          83.755
Zamkniecie        82.787
Wolumen            50197
Name: 54, dtype: object
55 Data          2017-03-21
Otwarcie          83.286
Zamkniecie         81.79
Wolumen            25528
Name: 55, dtype: object
56 Data          2017-03-22
Otwarcie           81.79
Zamkniecie        81.291
Wolumen             4856
Name: 56, dtype: object
57 Data          2017-03-23
Otwarcie           81.79
Zamkniecie        81.291
Wolumen             5464
Name: 57, dtype: object
58 Data          2017-03-24
Otwarcie          80.792
Zamkniecie        80.772
Wolumen             1978
Name: 58, dtype: object
59 Data          2017-03-27
Otwarcie          78.807
Zamkniecie        79.396
Wolumen             1973
Name: 59, dtype: object
60 Data          2017-03-28
Otwarcie          79.396
Zamkniecie        79.496
Wolumen             1775
Name: 60, dtype: object
61 Data          2017-03-29
Otwarcie          79.795
Zamkniecie        80.543
Wolumen             3451
Name: 61, dtype: object
62 Data          2017-03-30
Otwarcie          79.795
Zamkniecie        80.792
Wolumen             9138
Name: 62, dtype: object
63 Data          2017-03-31
Otwarcie          79.845
Zamkniecie         81.84
Wolumen             2114
Name: 63, dtype: object
64 Data          2017-04-03
Otwarcie           81.57
Zamkniecie          81.8
Wolumen              945
Name: 64, dtype: object
65 Data          2017-04-04
Otwarcie          79.964
Zamkniecie        79.795
Wolumen             2534
Name: 65, dtype: object
66 Data          2017-04-05
Otwarcie          79.805
Zamkniecie        80.792
Wolumen             4662
Name: 66, dtype: object
67 Data          2017-04-06
Otwarcie          80.523
Zamkniecie        80.792
Wolumen             1007
Name: 67, dtype: object
68 Data          2017-04-07
Otwarcie          81.181
Zamkniecie         81.79
Wolumen             3507
Name: 68, dtype: object
69 Data          2017-04-10
Otwarcie          80.792
Zamkniecie        79.097
Wolumen             3509
Name: 69, dtype: object
70 Data          2017-04-11
Otwarcie          79.107
Zamkniecie        77.591
Wolumen             3160
Name: 70, dtype: object
71 Data          2017-04-12
Otwarcie           77.78
Zamkniecie        78.259
Wolumen             4670
Name: 71, dtype: object
72 Data          2017-04-13
Otwarcie          78.289
Zamkniecie        79.585
Wolumen             1048
Name: 72, dtype: object
73 Data          2017-04-18
Otwarcie          78.448
Zamkniecie        79.286
Wolumen             1598
Name: 73, dtype: object
74 Data          2017-04-19
Otwarcie          78.289
Zamkniecie        78.289
Wolumen             8366
Name: 74, dtype: object
75 Data          2017-04-20
Otwarcie          78.249
Zamkniecie        79.745
Wolumen             3364
Name: 75, dtype: object
76 Data          2017-04-21
Otwarcie          79.795
Zamkniecie         81.76
Wolumen            30718
Name: 76, dtype: object
77 Data          2017-04-24
Otwarcie          83.416
Zamkniecie        82.787
Wolumen             3108
Name: 77, dtype: object
78 Data          2017-04-25
Otwarcie          81.291
Zamkniecie         81.79
Wolumen           231416
Name: 78, dtype: object
79 Data          2017-04-26
Otwarcie           81.79
Zamkniecie        78.777
Wolumen            16210
Name: 79, dtype: object
80 Data          2017-04-27
Otwarcie          78.997
Zamkniecie        79.097
Wolumen            38783
Name: 80, dtype: object

81 Data          2017-04-28
Otwarcie          79.097
Zamkniecie        79.047
Wolumen             6401
Name: 81, dtype: object
82 Data          2017-05-02
Otwarcie          79.795
Zamkniecie         81.56
Wolumen             8792
Name: 82, dtype: object
83 Data          2017-05-04
Otwarcie          81.291
Zamkniecie        79.675
Wolumen             2514
Name: 83, dtype: object
84 Data          2017-05-05
Otwarcie          80.443
Zamkniecie        79.276
Wolumen             2789
Name: 84, dtype: object
85 Data          2017-05-08
Otwarcie          79.037
Zamkniecie        78.797
Wolumen             1310
Name: 85, dtype: object
86 Data          2017-05-09
Otwarcie          78.897
Zamkniecie          77.8
Wolumen             6354
Name: 86, dtype: object
87 Data          2017-05-10
Otwarcie          78.578
Zamkniecie        77.561
Wolumen            30816
Name: 87, dtype: object
88 Data          2017-05-11
Otwarcie          77.561
Zamkniecie        77.301
Wolumen             4038
Name: 88, dtype: object
89 Data          2017-05-12
Otwarcie            77.8
Zamkniecie        76.982
Wolumen            56737
Name: 89, dtype: object
90 Data          2017-05-15
Otwarcie          76.803
Zamkniecie        76.214
Wolumen             3442
Name: 90, dtype: object
91 Data          2017-05-16
Otwarcie          75.875
Zamkniecie        75.955
Wolumen             7420
Name: 91, dtype: object
92 Data          2017-05-17
Otwarcie          75.805
Zamkniecie        77.002
Wolumen             4513
Name: 92, dtype: object
93 Data          2017-05-18
Otwarcie          77.002
Zamkniecie        78.797
Wolumen             6102
Name: 93, dtype: object
94 Data          2017-05-19
Otwarcie           77.62
Zamkniecie        77.431
Wolumen              842
Name: 94, dtype: object
95 Data          2017-05-22
Otwarcie          77.431
Zamkniecie        79.595
Wolumen             1884
Name: 95, dtype: object
96 Data          2017-05-23
Otwarcie         79.5954
Zamkniecie          77.8
Wolumen             1041
Name: 96, dtype: object
97 Data          2017-05-24
Otwarcie              78
Zamkniecie         79.45
Wolumen            21106
Name: 97, dtype: object
98 Data          2017-05-25
Otwarcie            79.3
Zamkniecie         79.19
Wolumen             4692
Name: 98, dtype: object
99 Data          2017-05-26
Otwarcie           79.75
Zamkniecie          78.5
Wolumen              989
Name: 99, dtype: object
100 Data          2017-05-29
Otwarcie            78.5
Zamkniecie          77.4
Wolumen            81752
Name: 100, dtype: object
101 Data          2017-05-30
Otwarcie            77.5
Zamkniecie         77.45
Wolumen            91769
Name: 101, dtype: object
102 Data          2017-05-31
Otwarcie              77
Zamkniecie            78
Wolumen             6589
Name: 102, dtype: object
103 Data          2017-06-01
Otwarcie            77.5
Zamkniecie          76.5
Wolumen            34301
Name: 103, dtype: object
104 Data          2017-06-02
Otwarcie           77.45
Zamkniecie         76.85
Wolumen            36404
Name: 104, dtype: object
105 Data          2017-06-05
Otwarcie           76.15
Zamkniecie          76.9
Wolumen             6296
Name: 105, dtype: object
106 Data          2017-06-06
Otwarcie           76.21
Zamkniecie         76.88
Wolumen            53420
Name: 106, dtype: object
107 Data          2017-06-07
Otwarcie           76.88
Zamkniecie          76.6
Wolumen              690
Name: 107, dtype: object
108 Data          2017-06-08
Otwarcie            76.5
Zamkniecie          76.4
Wolumen              945
Name: 108, dtype: object
109 Data          2017-06-09
Otwarcie            76.5
Zamkniecie          76.9
Wolumen              859
Name: 109, dtype: object
110 Data          2017-06-12
Otwarcie            76.9
Zamkniecie          76.9
Wolumen              663
Name: 110, dtype: object
111 Data          2017-06-13
Otwarcie           76.54
Zamkniecie          76.9
Wolumen              749
Name: 111, dtype: object
112 Data          2017-06-14
Otwarcie           76.66
Zamkniecie            77
Wolumen             3547
Name: 112, dtype: object
113 Data          2017-06-16
Otwarcie           76.61
Zamkniecie          78.5
Wolumen              533
Name: 113, dtype: object
114 Data          2017-06-19
Otwarcie           78.49
Zamkniecie          78.2
Wolumen              900
Name: 114, dtype: object
115 Data          2017-06-20
Otwarcie           78.32
Zamkniecie         79.64
Wolumen             2108
Name: 115, dtype: object
116 Data          2017-06-21
Otwarcie           79.69
Zamkniecie         79.35
Wolumen             2496
Name: 116, dtype: object
117 Data          2017-06-22
Otwarcie           79.05
Zamkniecie         79.69
Wolumen             2532
Name: 117, dtype: object
118 Data          2017-06-23
Otwarcie           79.99
Zamkniecie            80
Wolumen            21006
Name: 118, dtype: object
119 Data          2017-06-26
Otwarcie           80.75
Zamkniecie         81.48
Wolumen             3047
Name: 119, dtype: object
120 Data          2017-06-27
Otwarcie           81.49
Zamkniecie          83.5
Wolumen             6037
Name: 120, dtype: object
121 Data          2017-06-28
Otwarcie            83.5
Zamkniecie         82.43
Wolumen              707
Name: 121, dtype: object
122 Data          2017-06-29
Otwarcie            82.5
Zamkniecie          81.5
Wolumen             7370
Name: 122, dtype: object
123 Data          2017-06-30
Otwarcie            80.6
Zamkniecie         82.35
Wolumen             7554
Name: 123, dtype: object
124 Data          2017-07-03
Otwarcie           82.48
Zamkniecie            82
Wolumen             3584
Name: 124, dtype: object
125 Data          2017-07-04
Otwarcie           82.95
Zamkniecie            80
Wolumen             1196
Name: 125, dtype: object
126 Data          2017-07-05
Otwarcie              80
Zamkniecie            82
Wolumen            24720
Name: 126, dtype: object
127 Data          2017-07-06
Otwarcie           81.31
Zamkniecie         82.04
Wolumen             1002
Name: 127, dtype: object
128 Data          2017-07-07
Otwarcie           81.69
Zamkniecie          82.7
Wolumen             1738
Name: 128, dtype: object
129 Data          2017-07-10
Otwarcie           82.71
Zamkniecie          81.5
Wolumen              398
Name: 129, dtype: object
130 Data          2017-07-11
Otwarcie              82
Zamkniecie         80.91
Wolumen              585
Name: 130, dtype: object
131 Data          2017-07-12
Otwarcie              82
Zamkniecie          79.1
Wolumen             1412
Name: 131, dtype: object
132 Data          2017-07-13
Otwarcie           79.22
Zamkniecie            79
Wolumen             1344
Name: 132, dtype: object
133 Data          2017-07-14
Otwarcie            79.3
Zamkniecie          79.2
Wolumen              285
Name: 133, dtype: object
134 Data          2017-07-17
Otwarcie            79.4
Zamkniecie         79.71
Wolumen              212
Name: 134, dtype: object
135 Data          2017-07-18
Otwarcie           80.19
Zamkniecie         80.22
Wolumen             1242
Name: 135, dtype: object
136 Data          2017-07-19
Otwarcie            80.2
Zamkniecie         79.67
Wolumen              871
Name: 136, dtype: object
137 Data          2017-07-20
Otwarcie           79.01
Zamkniecie          77.2
Wolumen            14972
Name: 137, dtype: object
138 Data          2017-07-21
Otwarcie           78.15
Zamkniecie          76.6
Wolumen            18199
Name: 138, dtype: object
139 Data          2017-07-24
Otwarcie            76.6
Zamkniecie         76.55
Wolumen            19904
Name: 139, dtype: object
140 Data          2017-07-25
Otwarcie           76.64
Zamkniecie          77.5
Wolumen             4743
Name: 140, dtype: object
141 Data          2017-07-26
Otwarcie           77.81
Zamkniecie         77.94
Wolumen            23859
Name: 141, dtype: object
142 Data          2017-07-27
Otwarcie           78.39
Zamkniecie            78
Wolumen             4652
Name: 142, dtype: object
143 Data          2017-07-28
Otwarcie           78.19
Zamkniecie         77.98
Wolumen             3228
Name: 143, dtype: object
144 Data          2017-07-31
Otwarcie           72.73
Zamkniecie         67.77
Wolumen            81324
Name: 144, dtype: object
145 Data          2017-08-01
Otwarcie              68
Zamkniecie          65.3
Wolumen            35349
Name: 145, dtype: object
146 Data          2017-08-02
Otwarcie            65.3
Zamkniecie            66
Wolumen            67975
Name: 146, dtype: object
147 Data          2017-08-03
Otwarcie            66.7
Zamkniecie         67.45
Wolumen             3916
Name: 147, dtype: object
148 Data          2017-08-04
Otwarcie           67.45
Zamkniecie         68.49
Wolumen            22594
Name: 148, dtype: object
149 Data          2017-08-07
Otwarcie            68.9
Zamkniecie          68.5
Wolumen             1604
Name: 149, dtype: object
150 Data          2017-08-08
Otwarcie            68.5
Zamkniecie         68.59
Wolumen             1361
Name: 150, dtype: object
151 Data          2017-08-09
Otwarcie            68.4
Zamkniecie            68
Wolumen            12408
Name: 151, dtype: object
152 Data          2017-08-10
Otwarcie              68
Zamkniecie            70
Wolumen            32474
Name: 152, dtype: object
153 Data          2017-08-11
Otwarcie              72
Zamkniecie          70.6
Wolumen            16023
Name: 153, dtype: object
154 Data          2017-08-14
Otwarcie            70.7
Zamkniecie          70.7
Wolumen             1501
Name: 154, dtype: object
155 Data          2017-08-16
Otwarcie              71
Zamkniecie         70.83
Wolumen              742
Name: 155, dtype: object
156 Data          2017-08-17
Otwarcie           70.99
Zamkniecie          69.5
Wolumen             3523
Name: 156, dtype: object
157 Data          2017-08-18
Otwarcie            69.6
Zamkniecie            70
Wolumen             4372
Name: 157, dtype: object
158 Data          2017-08-21
Otwarcie            70.5
Zamkniecie            71
Wolumen            10037
Name: 158, dtype: object
159 Data          2017-08-22
Otwarcie              71
Zamkniecie            72
Wolumen             2978
Name: 159, dtype: object
160 Data          2017-08-23
Otwarcie              72
Zamkniecie            72
Wolumen              618
Name: 160, dtype: object
161 Data          2017-08-24
Otwarcie              71
Zamkniecie          73.4
Wolumen            63933
Name: 161, dtype: object

162 Data          2017-08-25
Otwarcie              73
Zamkniecie         71.07
Wolumen             1827
Name: 162, dtype: object
163 Data          2017-08-28
Otwarcie           70.55
Zamkniecie         73.37
Wolumen             7521
Name: 163, dtype: object
164 Data          2017-08-29
Otwarcie              73
Zamkniecie         72.99
Wolumen             6730
Name: 164, dtype: object
165 Data          2017-08-30
Otwarcie           72.95
Zamkniecie         74.02
Wolumen             7146
Name: 165, dtype: object
166 Data          2017-08-31
Otwarcie           74.02
Zamkniecie            76
Wolumen            10683
Name: 166, dtype: object
167 Data          2017-09-01
Otwarcie            77.5
Zamkniecie         75.01
Wolumen             7445
Name: 167, dtype: object
168 Data          2017-09-04
Otwarcie           74.45
Zamkniecie         74.45
Wolumen             1780
Name: 168, dtype: object
169 Data          2017-09-05
Otwarcie           73.52
Zamkniecie          73.1
Wolumen             1962
Name: 169, dtype: object
170 Data          2017-09-06
Otwarcie           72.06
Zamkniecie          72.5
Wolumen             3521
Name: 170, dtype: object
171 Data          2017-09-07
Otwarcie            72.5
Zamkniecie          72.5
Wolumen             1440
Name: 171, dtype: object
172 Data          2017-09-08
Otwarcie            71.7
Zamkniecie         72.45
Wolumen             3067
Name: 172, dtype: object
173 Data          2017-09-11
Otwarcie            72.5
Zamkniecie         71.98
Wolumen             2266
Name: 173, dtype: object
174 Data          2017-09-12
Otwarcie            71.9
Zamkniecie         71.32
Wolumen             5001
Name: 174, dtype: object
175 Data          2017-09-13
Otwarcie            71.7
Zamkniecie         70.13
Wolumen            57468
Name: 175, dtype: object
176 Data          2017-09-14
Otwarcie           70.13
Zamkniecie         67.59
Wolumen            45357
Name: 176, dtype: object
177 Data          2017-09-15
Otwarcie            67.6
Zamkniecie          72.1
Wolumen           283835
Name: 177, dtype: object
178 Data          2017-09-18
Otwarcie            72.5
Zamkniecie            71
Wolumen            37141
Name: 178, dtype: object
179 Data          2017-09-19
Otwarcie           69.15
Zamkniecie            71
Wolumen             3679
Name: 179, dtype: object
180 Data          2017-09-20
Otwarcie           70.51
Zamkniecie            71
Wolumen             2288
Name: 180, dtype: object
181 Data          2017-09-21
Otwarcie            71.5
Zamkniecie          70.9
Wolumen             2863
Name: 181, dtype: object
182 Data          2017-09-22
Otwarcie            70.9
Zamkniecie            71
Wolumen             5858
Name: 182, dtype: object
183 Data          2017-09-25
Otwarcie            70.6
Zamkniecie         70.58
Wolumen              681
Name: 183, dtype: object
184 Data          2017-09-26
Otwarcie           70.58
Zamkniecie            71
Wolumen             2136
Name: 184, dtype: object
185 Data          2017-09-27
Otwarcie            70.9
Zamkniecie         72.48
Wolumen            12314
Name: 185, dtype: object
186 Data          2017-09-28
Otwarcie           72.49
Zamkniecie         72.75
Wolumen             4534
Name: 186, dtype: object
187 Data          2017-09-29
Otwarcie           72.75
Zamkniecie         72.75
Wolumen             6967
Name: 187, dtype: object
188 Data          2017-10-02
Otwarcie           72.75
Zamkniecie            73
Wolumen             2642
Name: 188, dtype: object
189 Data          2017-10-03
Otwarcie           73.73
Zamkniecie         72.89
Wolumen              889
Name: 189, dtype: object
190 Data          2017-10-04
Otwarcie           72.89
Zamkniecie         73.22
Wolumen             1009
Name: 190, dtype: object
191 Data          2017-10-05
Otwarcie           73.11
Zamkniecie         72.89
Wolumen              953
Name: 191, dtype: object
192 Data          2017-10-06
Otwarcie           72.89
Zamkniecie          72.5
Wolumen             2349
Name: 192, dtype: object
193 Data          2017-10-09
Otwarcie              73
Zamkniecie            73
Wolumen             1804
Name: 193, dtype: object
194 Data          2017-10-10
Otwarcie              73
Zamkniecie            74
Wolumen             1812
Name: 194, dtype: object
195 Data          2017-10-11
Otwarcie              74
Zamkniecie            74
Wolumen             2566
Name: 195, dtype: object
196 Data          2017-10-12
Otwarcie            73.7
Zamkniecie         73.21
Wolumen              719
Name: 196, dtype: object
197 Data          2017-10-13
Otwarcie           72.81
Zamkniecie         72.44
Wolumen             1735
Name: 197, dtype: object
198 Data          2017-10-16
Otwarcie           74.25
Zamkniecie         72.97
Wolumen              330
Name: 198, dtype: object
199 Data          2017-10-17
Otwarcie           72.97
Zamkniecie         72.14
Wolumen             1855
Name: 199, dtype: object
200 Data          2017-10-18
Otwarcie           72.04
Zamkniecie         71.37
Wolumen             1548
Name: 200, dtype: object
201 Data          2017-10-19
Otwarcie           73.57
Zamkniecie         70.95
Wolumen             4840
Name: 201, dtype: object
202 Data          2017-10-20
Otwarcie           69.51
Zamkniecie         68.94
Wolumen             7140
Name: 202, dtype: object
203 Data          2017-10-23
Otwarcie            69.2
Zamkniecie         68.38
Wolumen             2963
Name: 203, dtype: object
204 Data          2017-10-24
Otwarcie              66
Zamkniecie         63.25
Wolumen           179561
Name: 204, dtype: object
205 Data          2017-10-25
Otwarcie           62.56
Zamkniecie            65
Wolumen            14087
Name: 205, dtype: object
206 Data          2017-10-26
Otwarcie           66.52
Zamkniecie          64.9
Wolumen             4076
Name: 206, dtype: object
207 Data          2017-10-27
Otwarcie              65
Zamkniecie          66.5
Wolumen              914
Name: 207, dtype: object
208 Data          2017-10-30
Otwarcie            66.5
Zamkniecie         66.76
Wolumen             1253
Name: 208, dtype: object
209 Data          2017-10-31
Otwarcie           67.34
Zamkniecie         66.52
Wolumen             1637
Name: 209, dtype: object
210 Data          2017-11-02
Otwarcie            66.4
Zamkniecie         64.65
Wolumen             2889
Name: 210, dtype: object
211 Data          2017-11-03
Otwarcie           64.65
Zamkniecie         63.25
Wolumen             1379
Name: 211, dtype: object
212 Data          2017-11-06
Otwarcie           63.25
Zamkniecie         62.16
Wolumen            25030
Name: 212, dtype: object
213 Data          2017-11-07
Otwarcie              62
Zamkniecie            62
Wolumen            35450
Name: 213, dtype: object
214 Data          2017-11-08
Otwarcie              62
Zamkniecie         61.89
Wolumen             1739
Name: 214, dtype: object
215 Data          2017-11-09
Otwarcie           61.15
Zamkniecie         60.42
Wolumen             2518
Name: 215, dtype: object
216 Data          2017-11-10
Otwarcie              60
Zamkniecie          61.5
Wolumen             6511
Name: 216, dtype: object
217 Data          2017-11-13
Otwarcie            61.5
Zamkniecie          61.4
Wolumen             1373
Name: 217, dtype: object
218 Data          2017-11-14
Otwarcie            61.4
Zamkniecie         61.35
Wolumen             1693
Name: 218, dtype: object
219 Data          2017-11-15
Otwarcie           60.45
Zamkniecie          61.3
Wolumen             6423
Name: 219, dtype: object
220 Data          2017-11-16
Otwarcie            61.4
Zamkniecie         60.89
Wolumen             1439
Name: 220, dtype: object
221 Data          2017-11-17
Otwarcie           60.02
Zamkniecie         60.79
Wolumen             2915
Name: 221, dtype: object
222 Data          2017-11-20
Otwarcie              61
Zamkniecie         59.98
Wolumen             3796
Name: 222, dtype: object
223 Data          2017-11-21
Otwarcie           60.01
Zamkniecie            60
Wolumen             6472
Name: 223, dtype: object
224 Data          2017-11-22
Otwarcie           60.03
Zamkniecie          60.2
Wolumen             3749
Name: 224, dtype: object
225 Data          2017-11-23
Otwarcie           60.65
Zamkniecie         60.45
Wolumen           179620
Name: 225, dtype: object
226 Data          2017-11-24
Otwarcie              61
Zamkniecie          60.5
Wolumen             3873
Name: 226, dtype: object
227 Data          2017-11-27
Otwarcie           61.19
Zamkniecie         60.98
Wolumen            26756
Name: 227, dtype: object
228 Data          2017-11-28
Otwarcie           60.61
Zamkniecie         61.43
Wolumen             2249
Name: 228, dtype: object
229 Data          2017-11-29
Otwarcie            61.5
Zamkniecie         60.19
Wolumen            37810
Name: 229, dtype: object
230 Data          2017-11-30
Otwarcie           60.35
Zamkniecie          59.6
Wolumen            13752
Name: 230, dtype: object
231 Data          2017-12-01
Otwarcie           60.35
Zamkniecie         58.25
Wolumen             5834
Name: 231, dtype: object
232 Data          2017-12-04
Otwarcie           58.25
Zamkniecie         59.55
Wolumen              980
Name: 232, dtype: object
233 Data          2017-12-05
Otwarcie           59.55
Zamkniecie          58.6
Wolumen             1490
Name: 233, dtype: object
234 Data          2017-12-06
Otwarcie           57.99
Zamkniecie          53.5
Wolumen            76928
Name: 234, dtype: object
235 Data          2017-12-07
Otwarcie            53.1
Zamkniecie         54.05
Wolumen            38356
Name: 235, dtype: object
236 Data          2017-12-08
Otwarcie           54.05
Zamkniecie            55
Wolumen             8167
Name: 236, dtype: object
237 Data          2017-12-11
Otwarcie              55
Zamkniecie         55.25
Wolumen             3608
Name: 237, dtype: object
238 Data          2017-12-12
Otwarcie           54.76
Zamkniecie         54.95
Wolumen            11539
Name: 238, dtype: object
239 Data          2017-12-13
Otwarcie           53.81
Zamkniecie          54.1
Wolumen             1095
Name: 239, dtype: object
240 Data          2017-12-14
Otwarcie           53.25
Zamkniecie         52.48
Wolumen             5176
Name: 240, dtype: object
241 Data          2017-12-15
Otwarcie           52.48
Zamkniecie          51.7
Wolumen            42294
Name: 241, dtype: object
242 Data          2017-12-18
Otwarcie           51.45
Zamkniecie            50
Wolumen            12068
Name: 242, dtype: object
243 Data          2017-12-19
Otwarcie           49.48
Zamkniecie            50
Wolumen             2418
Name: 243, dtype: object
244 Data          2017-12-20
Otwarcie            50.2
Zamkniecie         48.41
Wolumen             1664
Name: 244, dtype: object
245 Data          2017-12-21
Otwarcie           47.89
Zamkniecie          46.8
Wolumen            36611
Name: 245, dtype: object

246 Data          2017-12-22
Otwarcie            46.8
Zamkniecie          46.4
Wolumen             7655
Name: 246, dtype: object
247 Data          2017-12-27
Otwarcie            47.2
Zamkniecie          46.5
Wolumen             4497
Name: 247, dtype: object
248 Data          2017-12-28
Otwarcie           47.47
Zamkniecie         47.77
Wolumen             2977
Name: 248, dtype: object
249 Data          2017-12-29
Otwarcie           47.86
Zamkniecie            50
Wolumen             5424
Name: 249, dtype: object
250 Data          2018-01-03
Otwarcie            52.9
Zamkniecie          50.1
Wolumen             8975
Name: 250, dtype: object
251 Data          2018-01-04
Otwarcie            49.8
Zamkniecie          50.8
Wolumen           106313
Name: 251, dtype: object
252 Data          2018-01-05
Otwarcie            52.1
Zamkniecie          50.8
Wolumen            23478
Name: 252, dtype: object
253 Data          2018-01-08
Otwarcie              51
Zamkniecie            51
Wolumen            53748
Name: 253, dtype: object
254 Data          2018-01-09
Otwarcie            51.5
Zamkniecie          52.2
Wolumen             5036
Name: 254, dtype: object
255 Data          2018-01-10
Otwarcie            52.7
Zamkniecie          51.8
Wolumen             2998
Name: 255, dtype: object
256 Data          2018-01-11
Otwarcie            52.5
Zamkniecie            52
Wolumen             3369
Name: 256, dtype: object
257 Data          2018-01-12
Otwarcie            51.7
Zamkniecie          50.9
Wolumen             3025
Name: 257, dtype: object
258 Data          2018-01-15
Otwarcie            51.2
Zamkniecie         49.65
Wolumen             8153
Name: 258, dtype: object
259 Data          2018-01-16
Otwarcie            49.6
Zamkniecie         48.75
Wolumen             6313
Name: 259, dtype: object
260 Data          2018-01-17
Otwarcie           48.75
Zamkniecie            50
Wolumen             5080
Name: 260, dtype: object
261 Data          2018-01-18
Otwarcie           49.95
Zamkniecie          50.7
Wolumen            26490
Name: 261, dtype: object
262 Data          2018-01-19
Otwarcie              51
Zamkniecie          50.7
Wolumen             1372
Name: 262, dtype: object
263 Data          2018-01-22
Otwarcie              51
Zamkniecie          50.9
Wolumen             9870
Name: 263, dtype: object
264 Data          2018-01-23
Otwarcie              51
Zamkniecie         49.85
Wolumen             4024
Name: 264, dtype: object
265 Data          2018-01-24
Otwarcie            49.8
Zamkniecie            50
Wolumen             5133
Name: 265, dtype: object
266 Data          2018-01-25
Otwarcie            49.4
Zamkniecie          48.9
Wolumen             5711
Name: 266, dtype: object
267 Data          2018-01-26
Otwarcie              50
Zamkniecie          49.1
Wolumen             5764
Name: 267, dtype: object
268 Data          2018-01-29
Otwarcie           49.15
Zamkniecie          49.5
Wolumen            18678
Name: 268, dtype: object
269 Data          2018-01-30
Otwarcie            49.5
Zamkniecie          48.5
Wolumen             2255
Name: 269, dtype: object
270 Data          2018-01-31
Otwarcie           48.55
Zamkniecie         48.75
Wolumen             2876
Name: 270, dtype: object
271 Data          2018-02-01
Otwarcie              47
Zamkniecie            43
Wolumen           342725
Name: 271, dtype: object
272 Data          2018-02-02
Otwarcie              43
Zamkniecie            42
Wolumen            59908
Name: 272, dtype: object
273 Data          2018-02-05
Otwarcie            41.5
Zamkniecie          42.5
Wolumen            15525
Name: 273, dtype: object
274 Data          2018-02-06
Otwarcie              41
Zamkniecie            41
Wolumen           160643
Name: 274, dtype: object
275 Data          2018-02-07
Otwarcie            41.8
Zamkniecie          41.7
Wolumen            35158
Name: 275, dtype: object
276 Data          2018-02-08
Otwarcie              42
Zamkniecie          47.2
Wolumen           163206
Name: 276, dtype: object
277 Data          2018-02-09
Otwarcie            47.3
Zamkniecie            50
Wolumen            40698
Name: 277, dtype: object
278 Data          2018-02-12
Otwarcie           49.95
Zamkniecie          50.1
Wolumen            20516
Name: 278, dtype: object
279 Data          2018-02-13
Otwarcie            50.4
Zamkniecie          52.1
Wolumen            13007
Name: 279, dtype: object
280 Data          2018-02-14
Otwarcie            51.6
Zamkniecie          52.8
Wolumen            12074
Name: 280, dtype: object
281 Data          2018-02-15
Otwarcie            52.9
Zamkniecie          54.6
Wolumen             7998
Name: 281, dtype: object
282 Data          2018-02-16
Otwarcie            54.8
Zamkniecie          53.7
Wolumen            11639
Name: 282, dtype: object
283 Data          2018-02-19
Otwarcie            53.6
Zamkniecie          54.2
Wolumen             8014
Name: 283, dtype: object
284 Data          2018-02-20
Otwarcie            54.4
Zamkniecie          53.9
Wolumen            13151
Name: 284, dtype: object
285 Data          2018-02-21
Otwarcie              52
Zamkniecie            53
Wolumen             7144
Name: 285, dtype: object
286 Data          2018-02-22
Otwarcie            52.2
Zamkniecie            54
Wolumen             8212
Name: 286, dtype: object
287 Data          2018-02-23
Otwarcie            54.5
Zamkniecie          54.4
Wolumen            24277
Name: 287, dtype: object
288 Data          2018-02-26
Otwarcie            53.4
Zamkniecie            55
Wolumen             7848
Name: 288, dtype: object
289 Data          2018-02-27
Otwarcie              55
Zamkniecie          55.5
Wolumen             8995
Name: 289, dtype: object
290 Data          2018-02-28
Otwarcie              55
Zamkniecie          55.5
Wolumen            13355
Name: 290, dtype: object
291 Data          2018-03-01
Otwarcie            54.1
Zamkniecie          54.7
Wolumen             3760
Name: 291, dtype: object
292 Data          2018-03-02
Otwarcie              54
Zamkniecie            55
Wolumen             1367
Name: 292, dtype: object
293 Data          2018-03-05
Otwarcie            53.7
Zamkniecie          53.6
Wolumen             1080
Name: 293, dtype: object
294 Data          2018-03-06
Otwarcie            53.6
Zamkniecie          55.6
Wolumen             5687
Name: 294, dtype: object
295 Data          2018-03-07
Otwarcie            56.2
Zamkniecie          56.1
Wolumen           338940
Name: 295, dtype: object
296 Data          2018-03-08
Otwarcie            56.5
Zamkniecie          56.3
Wolumen           156345
Name: 296, dtype: object
297 Data          2018-03-09
Otwarcie            55.7
Zamkniecie            57
Wolumen             3884
Name: 297, dtype: object
298 Data          2018-03-12
Otwarcie            56.7
Zamkniecie          56.8
Wolumen             2636
Name: 298, dtype: object
299 Data          2018-03-13
Otwarcie            56.7
Zamkniecie          55.6
Wolumen           263803
Name: 299, dtype: object
300 Data          2018-03-14
Otwarcie            55.3
Zamkniecie          53.5
Wolumen             2162
Name: 300, dtype: object
301 Data          2018-03-15
Otwarcie            53.3
Zamkniecie            53
Wolumen             7428
Name: 301, dtype: object
302 Data          2018-03-16
Otwarcie            53.2
Zamkniecie          54.5
Wolumen             3423
Name: 302, dtype: object
303 Data          2018-03-19
Otwarcie            55.5
Zamkniecie          53.2
Wolumen             1735
Name: 303, dtype: object
304 Data          2018-03-20
Otwarcie            53.5
Zamkniecie          54.8
Wolumen             1144
Name: 304, dtype: object
305 Data          2018-03-21
Otwarcie            54.8
Zamkniecie          55.3
Wolumen            52786
Name: 305, dtype: object
306 Data          2018-03-22
Otwarcie              55
Zamkniecie          54.6
Wolumen            16161
Name: 306, dtype: object
307 Data          2018-03-23
Otwarcie            53.9
Zamkniecie            54
Wolumen             1502
Name: 307, dtype: object
308 Data          2018-03-26
Otwarcie            54.1
Zamkniecie            54
Wolumen             4831
Name: 308, dtype: object
309 Data          2018-03-27
Otwarcie            54.3
Zamkniecie          54.3
Wolumen            12876
Name: 309, dtype: object
310 Data          2018-03-28
Otwarcie              53
Zamkniecie            54
Wolumen             2291
Name: 310, dtype: object
311 Data          2018-03-29
Otwarcie            53.9
Zamkniecie          53.5
Wolumen             1618
Name: 311, dtype: object
312 Data          2018-04-03
Otwarcie              53
Zamkniecie          52.4
Wolumen             8245
Name: 312, dtype: object
313 Data          2018-04-04
Otwarcie            52.8
Zamkniecie          53.5
Wolumen             2432
Name: 313, dtype: object
314 Data          2018-04-05
Otwarcie            53.3
Zamkniecie            53
Wolumen             5520
Name: 314, dtype: object
315 Data          2018-04-06
Otwarcie              53
Zamkniecie            57
Wolumen            20029
Name: 315, dtype: object
316 Data          2018-04-09
Otwarcie              57
Zamkniecie          55.2
Wolumen            45534
Name: 316, dtype: object
317 Data          2018-04-10
Otwarcie            55.1
Zamkniecie            55
Wolumen           105270
Name: 317, dtype: object
318 Data          2018-04-11
Otwarcie              55
Zamkniecie            54
Wolumen           106571
Name: 318, dtype: object
319 Data          2018-04-12
Otwarcie            53.4
Zamkniecie            53
Wolumen             6179
Name: 319, dtype: object
320 Data          2018-04-13
Otwarcie            53.1
Zamkniecie          53.6
Wolumen             2260
Name: 320, dtype: object
321 Data          2018-04-16
Otwarcie            53.7
Zamkniecie          53.2
Wolumen            12615
Name: 321, dtype: object
322 Data          2018-04-17
Otwarcie            53.7
Zamkniecie            53
Wolumen              437
Name: 322, dtype: object
323 Data          2018-04-18
Otwarcie            54.9
Zamkniecie          52.9
Wolumen              969
Name: 323, dtype: object
324 Data          2018-04-19
Otwarcie            52.7
Zamkniecie          51.6
Wolumen            51704
Name: 324, dtype: object
325 Data          2018-04-20
Otwarcie            51.6
Zamkniecie          50.5
Wolumen            35471
Name: 325, dtype: object
326 Data          2018-04-23
Otwarcie            50.4
Zamkniecie          50.5
Wolumen             8144
Name: 326, dtype: object
327 Data          2018-04-24
Otwarcie              51
Zamkniecie            50
Wolumen            12780
Name: 327, dtype: object
328 Data          2018-04-25
Otwarcie              50
Zamkniecie            51
Wolumen              918
Name: 328, dtype: object
329 Data          2018-04-26
Otwarcie              51
Zamkniecie          50.7
Wolumen           138973
Name: 329, dtype: object

330 Data          2018-04-27
Otwarcie            52.7
Zamkniecie          50.6
Wolumen             2815
Name: 330, dtype: object
331 Data          2018-04-30
Otwarcie            50.6
Zamkniecie          50.2
Wolumen              575
Name: 331, dtype: object
332 Data          2018-05-02
Otwarcie            49.9
Zamkniecie          50.2
Wolumen             2802
Name: 332, dtype: object
333 Data          2018-05-04
Otwarcie            50.5
Zamkniecie          50.1
Wolumen             5270
Name: 333, dtype: object
334 Data          2018-05-07
Otwarcie              50
Zamkniecie          49.5
Wolumen            52803
Name: 334, dtype: object
335 Data          2018-05-08
Otwarcie            49.5
Zamkniecie          50.2
Wolumen             1298
Name: 335, dtype: object
336 Data          2018-05-09
Otwarcie            48.2
Zamkniecie          49.5
Wolumen            31228
Name: 336, dtype: object
337 Data          2018-05-10
Otwarcie            48.3
Zamkniecie            50
Wolumen            91332
Name: 337, dtype: object
338 Data          2018-05-11
Otwarcie            48.6
Zamkniecie          51.7
Wolumen             4145
Name: 338, dtype: object
339 Data          2018-05-14
Otwarcie            51.7
Zamkniecie            53
Wolumen           139864
Name: 339, dtype: object
340 Data          2018-05-15
Otwarcie            52.7
Zamkniecie          49.8
Wolumen             3097
Name: 340, dtype: object
341 Data          2018-05-16
Otwarcie            49.8
Zamkniecie          50.1
Wolumen            15986
Name: 341, dtype: object
342 Data          2018-05-17
Otwarcie            50.2
Zamkniecie            51
Wolumen              601
Name: 342, dtype: object
343 Data          2018-05-18
Otwarcie            51.7
Zamkniecie          50.4
Wolumen           201320
Name: 343, dtype: object
344 Data          2018-05-21
Otwarcie            51.9
Zamkniecie          51.7
Wolumen           202501
Name: 344, dtype: object
345 Data          2018-05-22
Otwarcie            51.6
Zamkniecie          49.5
Wolumen             1153
Name: 345, dtype: object
346 Data          2018-05-23
Otwarcie            50.5
Zamkniecie          50.5
Wolumen             5380
Name: 346, dtype: object
347 Data          2018-05-24
Otwarcie            50.8
Zamkniecie            50
Wolumen             2677
Name: 347, dtype: object
348 Data          2018-05-25
Otwarcie              50
Zamkniecie            54
Wolumen            56145
Name: 348, dtype: object
349 Data          2018-05-28
Otwarcie              54
Zamkniecie          52.3
Wolumen             5896
Name: 349, dtype: object
350 Data          2018-05-29
Otwarcie              52
Zamkniecie          52.2
Wolumen            30563
Name: 350, dtype: object
351 Data          2018-05-30
Otwarcie            52.2
Zamkniecie          51.2
Wolumen             6243
Name: 351, dtype: object
352 Data          2018-06-01
Otwarcie            51.2
Zamkniecie          50.6
Wolumen              618
Name: 352, dtype: object
353 Data          2018-06-04
Otwarcie            50.3
Zamkniecie          50.3
Wolumen              354
Name: 353, dtype: object
354 Data          2018-06-05
Otwarcie            50.6
Zamkniecie            50
Wolumen            28195
Name: 354, dtype: object
355 Data          2018-06-06
Otwarcie            50.5
Zamkniecie          49.5
Wolumen             7391
Name: 355, dtype: object
356 Data          2018-06-07
Otwarcie              50
Zamkniecie            51
Wolumen           128501
Name: 356, dtype: object
357 Data          2018-06-08
Otwarcie              51
Zamkniecie          50.9
Wolumen              966
Name: 357, dtype: object
358 Data          2018-06-11
Otwarcie            49.9
Zamkniecie          49.7
Wolumen             2552
Name: 358, dtype: object
359 Data          2018-06-12
Otwarcie           49.95
Zamkniecie         49.95
Wolumen              552
Name: 359, dtype: object
360 Data          2018-06-13
Otwarcie            49.7
Zamkniecie          49.3
Wolumen              709
Name: 360, dtype: object
361 Data          2018-06-14
Otwarcie           49.05
Zamkniecie            49
Wolumen             5418
Name: 361, dtype: object
362 Data          2018-06-15
Otwarcie            49.6
Zamkniecie            49
Wolumen             2865
Name: 362, dtype: object
363 Data          2018-06-18
Otwarcie           48.65
Zamkniecie          48.8
Wolumen              959
Name: 363, dtype: object
364 Data          2018-06-19
Otwarcie           48.65
Zamkniecie         47.05
Wolumen            31058
Name: 364, dtype: object
365 Data          2018-06-20
Otwarcie              47
Zamkniecie            48
Wolumen            10322
Name: 365, dtype: object
366 Data          2018-06-21
Otwarcie              49
Zamkniecie         47.35
Wolumen            30761
Name: 366, dtype: object
367 Data          2018-06-22
Otwarcie            48.3
Zamkniecie         47.45
Wolumen             1819
Name: 367, dtype: object
368 Data          2018-06-25
Otwarcie           45.25
Zamkniecie            48
Wolumen            11484
Name: 368, dtype: object
369 Data          2018-06-26
Otwarcie              48
Zamkniecie          46.5
Wolumen            30622
Name: 369, dtype: object
370 Data          2018-06-27
Otwarcie              47
Zamkniecie            47
Wolumen            17072
Name: 370, dtype: object
371 Data          2018-06-28
Otwarcie              47
Zamkniecie          47.5
Wolumen             8955
Name: 371, dtype: object
372 Data          2018-06-29
Otwarcie            47.5
Zamkniecie         47.35
Wolumen            11352
Name: 372, dtype: object
373 Data          2018-07-02
Otwarcie              47
Zamkniecie            46
Wolumen             2873
Name: 373, dtype: object
374 Data          2018-07-03
Otwarcie           45.95
Zamkniecie          45.2
Wolumen            10842
Name: 374, dtype: object
375 Data          2018-07-04
Otwarcie            45.2
Zamkniecie            44
Wolumen            61509
Name: 375, dtype: object
376 Data          2018-07-05
Otwarcie              44
Zamkniecie          44.3
Wolumen             1748
Name: 376, dtype: object
377 Data          2018-07-06
Otwarcie              45
Zamkniecie          44.6
Wolumen            31348
Name: 377, dtype: object
378 Data          2018-07-09
Otwarcie              45
Zamkniecie            45
Wolumen           102318
Name: 378, dtype: object
379 Data          2018-07-10
Otwarcie              45
Zamkniecie         44.55
Wolumen              798
Name: 379, dtype: object
380 Data          2018-07-11
Otwarcie           44.45
Zamkniecie          42.6
Wolumen            53756
Name: 380, dtype: object
381 Data          2018-07-12
Otwarcie            42.9
Zamkniecie         42.95
Wolumen              725
Name: 381, dtype: object
382 Data          2018-07-13
Otwarcie              43
Zamkniecie          41.7
Wolumen            42951
Name: 382, dtype: object
383 Data          2018-07-16
Otwarcie           42.25
Zamkniecie            41
Wolumen            44344
Name: 383, dtype: object
384 Data          2018-07-17
Otwarcie              41
Zamkniecie          39.5
Wolumen             8425
Name: 384, dtype: object
385 Data          2018-07-18
Otwarcie            39.5
Zamkniecie          39.3
Wolumen             3614
Name: 385, dtype: object
386 Data          2018-07-19
Otwarcie            39.3
Zamkniecie            40
Wolumen             3117
Name: 386, dtype: object
387 Data          2018-07-20
Otwarcie              40
Zamkniecie         39.85
Wolumen             1838
Name: 387, dtype: object
388 Data          2018-07-23
Otwarcie              40
Zamkniecie          39.5
Wolumen             2266
Name: 388, dtype: object
389 Data          2018-07-24
Otwarcie           39.95
Zamkniecie         39.55
Wolumen            36570
Name: 389, dtype: object
390 Data          2018-07-25
Otwarcie              40
Zamkniecie            40
Wolumen            22879
Name: 390, dtype: object
391 Data          2018-07-26
Otwarcie           40.15
Zamkniecie          40.6
Wolumen            34156
Name: 391, dtype: object
392 Data          2018-07-27
Otwarcie              47
Zamkniecie          48.5
Wolumen           299514
Name: 392, dtype: object
393 Data          2018-07-30
Otwarcie            49.5
Zamkniecie          45.5
Wolumen           181262
Name: 393, dtype: object
394 Data          2018-07-31
Otwarcie           45.65
Zamkniecie            46
Wolumen            55189
Name: 394, dtype: object
395 Data          2018-08-01
Otwarcie            46.2
Zamkniecie          45.7
Wolumen             8503
Name: 395, dtype: object
396 Data          2018-08-02
Otwarcie            46.1
Zamkniecie            46
Wolumen             2107
Name: 396, dtype: object
397 Data          2018-08-03
Otwarcie              46
Zamkniecie            46
Wolumen             9027
Name: 397, dtype: object
398 Data          2018-08-06
Otwarcie              46
Zamkniecie          46.4
Wolumen             9574
Name: 398, dtype: object
399 Data          2018-08-07
Otwarcie            46.4
Zamkniecie          46.4
Wolumen            13162
Name: 399, dtype: object
400 Data          2018-08-08
Otwarcie            46.9
Zamkniecie            46
Wolumen            61973
Name: 400, dtype: object
401 Data          2018-08-09
Otwarcie              46
Zamkniecie         45.95
Wolumen            11832
Name: 401, dtype: object
402 Data          2018-08-10
Otwarcie            45.9
Zamkniecie          45.1
Wolumen            10585
Name: 402, dtype: object
403 Data          2018-08-13
Otwarcie              45
Zamkniecie            45
Wolumen             6892
Name: 403, dtype: object
404 Data          2018-08-14
Otwarcie              45
Zamkniecie         44.85
Wolumen             5162
Name: 404, dtype: object
405 Data          2018-08-16
Otwarcie            44.7
Zamkniecie            45
Wolumen            13468
Name: 405, dtype: object
406 Data          2018-08-17
Otwarcie            45.9
Zamkniecie         44.75
Wolumen             6364
Name: 406, dtype: object
407 Data          2018-08-20
Otwarcie              45
Zamkniecie         44.35
Wolumen             6753
Name: 407, dtype: object
408 Data          2018-08-21
Otwarcie            44.9
Zamkniecie            45
Wolumen             1152
Name: 408, dtype: object

409 Data          2018-08-22
Otwarcie              45
Zamkniecie            45
Wolumen            10774
Name: 409, dtype: object
410 Data          2018-08-23
Otwarcie              45
Zamkniecie         44.95
Wolumen              964
Name: 410, dtype: object
411 Data          2018-08-24
Otwarcie              45
Zamkniecie            45
Wolumen            16902
Name: 411, dtype: object
412 Data          2018-08-27
Otwarcie              45
Zamkniecie            45
Wolumen             1440
Name: 412, dtype: object
413 Data          2018-08-28
Otwarcie              45
Zamkniecie            45
Wolumen            10004
Name: 413, dtype: object
414 Data          2018-08-29
Otwarcie              45
Zamkniecie            45
Wolumen              490
Name: 414, dtype: object
415 Data          2018-08-30
Otwarcie              45
Zamkniecie         44.95
Wolumen             4221
Name: 415, dtype: object
416 Data          2018-08-31
Otwarcie            44.5
Zamkniecie            45
Wolumen             4413
Name: 416, dtype: object
417 Data          2018-09-03
Otwarcie           44.95
Zamkniecie            45
Wolumen            22103
Name: 417, dtype: object
418 Data          2018-09-04
Otwarcie              45
Zamkniecie         44.05
Wolumen              608
Name: 418, dtype: object
419 Data          2018-09-05
Otwarcie           44.05
Zamkniecie            44
Wolumen             1807
Name: 419, dtype: object
420 Data          2018-09-06
Otwarcie              44
Zamkniecie          41.5
Wolumen            58840
Name: 420, dtype: object
421 Data          2018-09-07
Otwarcie            41.5
Zamkniecie          43.3
Wolumen            72049
Name: 421, dtype: object
422 Data          2018-09-10
Otwarcie           44.95
Zamkniecie          43.5
Wolumen             2481
Name: 422, dtype: object
423 Data          2018-09-11
Otwarcie            43.5
Zamkniecie          43.3
Wolumen            23523
Name: 423, dtype: object
424 Data          2018-09-12
Otwarcie           43.25
Zamkniecie          43.1
Wolumen           115655
Name: 424, dtype: object
425 Data          2018-09-13
Otwarcie            43.2
Zamkniecie          43.3
Wolumen            11552
Name: 425, dtype: object
426 Data          2018-09-14
Otwarcie           42.45
Zamkniecie            42
Wolumen            29542
Name: 426, dtype: object
427 Data          2018-09-17
Otwarcie              42
Zamkniecie            43
Wolumen            11880
Name: 427, dtype: object
428 Data          2018-09-18
Otwarcie              43
Zamkniecie         46.15
Wolumen             4375
Name: 428, dtype: object
429 Data          2018-09-19
Otwarcie              46
Zamkniecie          44.8
Wolumen             2198
Name: 429, dtype: object
430 Data          2018-09-20
Otwarcie            46.5
Zamkniecie            45
Wolumen            17784
Name: 430, dtype: object
431 Data          2018-09-21
Otwarcie            45.2
Zamkniecie          43.1
Wolumen            18474
Name: 431, dtype: object
432 Data          2018-09-24
Otwarcie            44.8
Zamkniecie          43.2
Wolumen            27376
Name: 432, dtype: object
433 Data          2018-09-25
Otwarcie            43.9
Zamkniecie          43.5
Wolumen              137
Name: 433, dtype: object
434 Data          2018-09-26
Otwarcie           44.35
Zamkniecie         43.45
Wolumen              594
Name: 434, dtype: object
435 Data          2018-09-27
Otwarcie           43.25
Zamkniecie          44.1
Wolumen              262
Name: 435, dtype: object
436 Data          2018-09-28
Otwarcie              44
Zamkniecie            43
Wolumen             4005
Name: 436, dtype: object
437 Data          2018-10-01
Otwarcie            43.3
Zamkniecie         43.15
Wolumen            46017
Name: 437, dtype: object
438 Data          2018-10-02
Otwarcie            43.4
Zamkniecie          43.1
Wolumen              767
Name: 438, dtype: object
439 Data          2018-10-03
Otwarcie            42.3
Zamkniecie         42.65
Wolumen              107
Name: 439, dtype: object
440 Data          2018-10-04
Otwarcie            42.6
Zamkniecie          42.5
Wolumen              624
Name: 440, dtype: object
441 Data          2018-10-05
Otwarcie            42.8
Zamkniecie         42.25
Wolumen            22052
Name: 441, dtype: object
442 Data          2018-10-08
Otwarcie              42
Zamkniecie          40.8
Wolumen             4145
Name: 442, dtype: object
443 Data          2018-10-09
Otwarcie            40.4
Zamkniecie         38.25
Wolumen            23727
Name: 443, dtype: object
444 Data          2018-10-10
Otwarcie           38.75
Zamkniecie          37.9
Wolumen             6661
Name: 444, dtype: object
445 Data          2018-10-11
Otwarcie              37
Zamkniecie          36.9
Wolumen            52604
Name: 445, dtype: object
446 Data          2018-10-12
Otwarcie            37.4
Zamkniecie            37
Wolumen             2375
Name: 446, dtype: object
447 Data          2018-10-15
Otwarcie              36
Zamkniecie          38.3
Wolumen             7060
Name: 447, dtype: object
448 Data          2018-10-16
Otwarcie            37.8
Zamkniecie            38
Wolumen             4944
Name: 448, dtype: object
449 Data          2018-10-17
Otwarcie              38
Zamkniecie            40
Wolumen            10261
Name: 449, dtype: object
450 Data          2018-10-18
Otwarcie            40.2
Zamkniecie            40
Wolumen             8889
Name: 450, dtype: object
451 Data          2018-10-19
Otwarcie              40
Zamkniecie          37.5
Wolumen            48986
Name: 451, dtype: object
452 Data          2018-10-22
Otwarcie              38
Zamkniecie            37
Wolumen             3135
Name: 452, dtype: object
453 Data          2018-10-23
Otwarcie              37
Zamkniecie          35.4
Wolumen             2225
Name: 453, dtype: object
454 Data          2018-10-24
Otwarcie            35.4
Zamkniecie          34.5
Wolumen            45255
Name: 454, dtype: object
455 Data          2018-10-25
Otwarcie            34.1
Zamkniecie          33.3
Wolumen            47990
Name: 455, dtype: object
456 Data          2018-10-26
Otwarcie              33
Zamkniecie          32.5
Wolumen            21067
Name: 456, dtype: object
457 Data          2018-10-29
Otwarcie            32.4
Zamkniecie          24.5
Wolumen           273927
Name: 457, dtype: object
458 Data          2018-10-30
Otwarcie              25
Zamkniecie          25.6
Wolumen           167188
Name: 458, dtype: object
459 Data          2018-10-31
Otwarcie           25.85
Zamkniecie          25.1
Wolumen             9250
Name: 459, dtype: object
460 Data          2018-11-02
Otwarcie           25.05
Zamkniecie         25.05
Wolumen             9375
Name: 460, dtype: object
461 Data          2018-11-05
Otwarcie            25.5
Zamkniecie            25
Wolumen             3796
Name: 461, dtype: object
462 Data          2018-11-06
Otwarcie              25
Zamkniecie         23.95
Wolumen           316266
Name: 462, dtype: object
463 Data          2018-11-07
Otwarcie            24.3
Zamkniecie          23.5
Wolumen            11283
Name: 463, dtype: object
464 Data          2018-11-08
Otwarcie            23.4
Zamkniecie         23.55
Wolumen             2584
Name: 464, dtype: object
465 Data          2018-11-09
Otwarcie            23.7
Zamkniecie            23
Wolumen            16333
Name: 465, dtype: object
466 Data          2018-11-13
Otwarcie            22.7
Zamkniecie            22
Wolumen           107495
Name: 466, dtype: object
467 Data          2018-11-14
Otwarcie              22
Zamkniecie          22.9
Wolumen             2385
Name: 467, dtype: object
468 Data          2018-11-15
Otwarcie            22.5
Zamkniecie          22.9
Wolumen            38548
Name: 468, dtype: object
469 Data          2018-11-16
Otwarcie            22.9
Zamkniecie          21.5
Wolumen            24828
Name: 469, dtype: object
470 Data          2018-11-19
Otwarcie            20.7
Zamkniecie          21.9
Wolumen           129388
Name: 470, dtype: object
471 Data          2018-11-20
Otwarcie            21.2
Zamkniecie          20.6
Wolumen            13173
Name: 471, dtype: object
472 Data          2018-11-21
Otwarcie           20.55
Zamkniecie            21
Wolumen            12929
Name: 472, dtype: object
473 Data          2018-11-22
Otwarcie              21
Zamkniecie         20.55
Wolumen            13781
Name: 473, dtype: object
474 Data          2018-11-23
Otwarcie            20.7
Zamkniecie            21
Wolumen            26154
Name: 474, dtype: object
475 Data          2018-11-26
Otwarcie              21
Zamkniecie          20.8
Wolumen            42155
Name: 475, dtype: object
476 Data          2018-11-27
Otwarcie            21.5
Zamkniecie          20.7
Wolumen            77268
Name: 476, dtype: object
477 Data          2018-11-28
Otwarcie            20.5
Zamkniecie         20.35
Wolumen           250151
Name: 477, dtype: object
478 Data          2018-11-29
Otwarcie           20.65
Zamkniecie            21
Wolumen            13779
Name: 478, dtype: object
479 Data          2018-11-30
Otwarcie              21
Zamkniecie          20.7
Wolumen            13647
Name: 479, dtype: object
480 Data          2018-12-03
Otwarcie              21
Zamkniecie          21.7
Wolumen            68783
Name: 480, dtype: object

481 Data          2018-12-04
Otwarcie              22
Zamkniecie          22.5
Wolumen           353461
Name: 481, dtype: object
482 Data          2018-12-05
Otwarcie           21.95
Zamkniecie         23.95
Wolumen            51980
Name: 482, dtype: object
483 Data          2018-12-06
Otwarcie            23.9
Zamkniecie         24.05
Wolumen            43293
Name: 483, dtype: object
484 Data          2018-12-07
Otwarcie           24.25
Zamkniecie            25
Wolumen            67506
Name: 484, dtype: object
485 Data          2018-12-10
Otwarcie           24.85
Zamkniecie          23.8
Wolumen            16557
Name: 485, dtype: object
486 Data          2018-12-11
Otwarcie            24.1
Zamkniecie          24.6
Wolumen            19043
Name: 486, dtype: object
487 Data          2018-12-12
Otwarcie            25.5
Zamkniecie          24.8
Wolumen             9005
Name: 487, dtype: object
488 Data          2018-12-13
Otwarcie            25.4
Zamkniecie         24.45
Wolumen            12834
Name: 488, dtype: object
489 Data          2018-12-14
Otwarcie            24.7
Zamkniecie          23.1
Wolumen            16592
Name: 489, dtype: object
490 Data          2018-12-17
Otwarcie            22.9
Zamkniecie          22.6
Wolumen            13764
Name: 490, dtype: object
491 Data          2018-12-18
Otwarcie            22.5
Zamkniecie          22.1
Wolumen            23802
Name: 491, dtype: object
492 Data          2018-12-19
Otwarcie            21.9
Zamkniecie         22.45
Wolumen            71883
Name: 492, dtype: object
493 Data          2018-12-20
Otwarcie           22.45
Zamkniecie         22.65
Wolumen            41918
Name: 493, dtype: object
494 Data          2018-12-21
Otwarcie           22.45
Zamkniecie          22.5
Wolumen            24989
Name: 494, dtype: object
495 Data          2018-12-27
Otwarcie            22.9
Zamkniecie          22.5
Wolumen             3055
Name: 495, dtype: object
496 Data          2018-12-28
Otwarcie           22.45
Zamkniecie         22.75
Wolumen             5059
Name: 496, dtype: object
497 Data          2019-01-02
Otwarcie           22.75
Zamkniecie         23.95
Wolumen            12478
Name: 497, dtype: object
498 Data          2019-01-03
Otwarcie            23.8
Zamkniecie         23.05
Wolumen             8608
Name: 498, dtype: object
499 Data          2019-01-04
Otwarcie           23.05
Zamkniecie         23.45
Wolumen             2021
Name: 499, dtype: object
500 Data          2019-01-07
Otwarcie            23.5
Zamkniecie          22.7
Wolumen             7736
Name: 500, dtype: object
501 Data          2019-01-08
Otwarcie           22.75
Zamkniecie          22.4
Wolumen             9846
Name: 501, dtype: object
502 Data          2019-01-09
Otwarcie            22.5
Zamkniecie          22.5
Wolumen             7142
Name: 502, dtype: object
503 Data          2019-01-10
Otwarcie            22.7
Zamkniecie          22.6
Wolumen            17776
Name: 503, dtype: object
504 Data          2019-01-11
Otwarcie           22.85
Zamkniecie          22.5
Wolumen             9576
Name: 504, dtype: object
505 Data          2019-01-14
Otwarcie           22.75
Zamkniecie         22.55
Wolumen             3058
Name: 505, dtype: object
506 Data          2019-01-15
Otwarcie           22.55
Zamkniecie            22
Wolumen            19106
Name: 506, dtype: object
507 Data          2019-01-16
Otwarcie              22
Zamkniecie          22.4
Wolumen            11917
Name: 507, dtype: object
508 Data          2019-01-17
Otwarcie            22.4
Zamkniecie          22.6
Wolumen             5746
Name: 508, dtype: object
509 Data          2019-01-18
Otwarcie            22.7
Zamkniecie          22.6
Wolumen            33823
Name: 509, dtype: object
510 Data          2019-01-21
Otwarcie            22.7
Zamkniecie         23.35
Wolumen            24382
Name: 510, dtype: object
511 Data          2019-01-22
Otwarcie            23.5
Zamkniecie         24.25
Wolumen            16241
Name: 511, dtype: object
512 Data          2019-01-23
Otwarcie           24.25
Zamkniecie          24.8
Wolumen             6362
Name: 512, dtype: object
513 Data          2019-01-24
Otwarcie            24.9
Zamkniecie         24.35
Wolumen             6868
Name: 513, dtype: object
514 Data          2019-01-25
Otwarcie           24.35
Zamkniecie          24.1
Wolumen             8815
Name: 514, dtype: object
515 Data          2019-01-28
Otwarcie            24.1
Zamkniecie         24.05
Wolumen             4685
Name: 515, dtype: object
516 Data          2019-01-29
Otwarcie              24
Zamkniecie         23.55
Wolumen            72542
Name: 516, dtype: object
517 Data          2019-01-30
Otwarcie           23.85
Zamkniecie          23.5
Wolumen            29746
Name: 517, dtype: object
518 Data          2019-01-31
Otwarcie           23.55
Zamkniecie          23.9
Wolumen            16931
Name: 518, dtype: object
519 Data          2019-02-01
Otwarcie            23.9
Zamkniecie         23.95
Wolumen            29077
Name: 519, dtype: object
520 Data          2019-02-04
Otwarcie            24.2
Zamkniecie          25.2
Wolumen             8615
Name: 520, dtype: object
521 Data          2019-02-05
Otwarcie            25.4
Zamkniecie         26.15
Wolumen            32601
Name: 521, dtype: object
522 Data          2019-02-06
Otwarcie            26.3
Zamkniecie          25.6
Wolumen            12218
Name: 522, dtype: object
523 Data          2019-02-07
Otwarcie            25.9
Zamkniecie          25.5
Wolumen             4661
Name: 523, dtype: object
524 Data          2019-02-08
Otwarcie            25.4
Zamkniecie          26.3
Wolumen             8003
Name: 524, dtype: object
525 Data          2019-02-11
Otwarcie              26
Zamkniecie          25.9
Wolumen            13667
Name: 525, dtype: object
526 Data          2019-02-12
Otwarcie            25.9
Zamkniecie         24.95
Wolumen            22223
Name: 526, dtype: object
527 Data          2019-02-13
Otwarcie            25.1
Zamkniecie            24
Wolumen            13796
Name: 527, dtype: object
528 Data          2019-02-14
Otwarcie           23.85
Zamkniecie            24
Wolumen            55679
Name: 528, dtype: object
529 Data          2019-02-15
Otwarcie            24.4
Zamkniecie          24.7
Wolumen            11279
Name: 529, dtype: object
530 Data          2019-02-18
Otwarcie            24.8
Zamkniecie         24.65
Wolumen             3902
Name: 530, dtype: object
531 Data          2019-02-19
Otwarcie           24.45
Zamkniecie          24.1
Wolumen             3909
Name: 531, dtype: object
532 Data          2019-02-20
Otwarcie            23.9
Zamkniecie          23.5
Wolumen            13195
Name: 532, dtype: object
533 Data          2019-02-21
Otwarcie           23.45
Zamkniecie         23.95
Wolumen             4439
Name: 533, dtype: object
534 Data          2019-02-22
Otwarcie            23.9
Zamkniecie          24.1
Wolumen             4000
Name: 534, dtype: object
535 Data          2019-02-25
Otwarcie            24.1
Zamkniecie         24.85
Wolumen            15977
Name: 535, dtype: object
536 Data          2019-02-26
Otwarcie           24.95
Zamkniecie         25.35
Wolumen            29626
Name: 536, dtype: object
537 Data          2019-02-27
Otwarcie            25.8
Zamkniecie            25
Wolumen            15033
Name: 537, dtype: object
538 Data          2019-02-28
Otwarcie            25.3
Zamkniecie          24.8
Wolumen             7211
Name: 538, dtype: object
539 Data          2019-03-01
Otwarcie            25.1
Zamkniecie          24.8
Wolumen             2635
Name: 539, dtype: object
540 Data          2019-03-04
Otwarcie           24.85
Zamkniecie          24.6
Wolumen             6639
Name: 540, dtype: object
541 Data          2019-03-05
Otwarcie            24.6
Zamkniecie          24.5
Wolumen             4650
Name: 541, dtype: object
542 Data          2019-03-06
Otwarcie           24.65
Zamkniecie          24.5
Wolumen             1512
Name: 542, dtype: object
543 Data          2019-03-07
Otwarcie            24.7
Zamkniecie         24.35
Wolumen             1431
Name: 543, dtype: object
544 Data          2019-03-08
Otwarcie            24.2
Zamkniecie            24
Wolumen             6500
Name: 544, dtype: object
545 Data          2019-03-11
Otwarcie              24
Zamkniecie          22.4
Wolumen            37754
Name: 545, dtype: object
546 Data          2019-03-12
Otwarcie            22.3
Zamkniecie         22.25
Wolumen            98805
Name: 546, dtype: object
547 Data          2019-03-13
Otwarcie           22.35
Zamkniecie          22.5
Wolumen             9966
Name: 547, dtype: object
548 Data          2019-03-14
Otwarcie            22.8
Zamkniecie            23
Wolumen            48817
Name: 548, dtype: object
549 Data          2019-03-15
Otwarcie              23
Zamkniecie         24.35
Wolumen            51347
Name: 549, dtype: object
550 Data          2019-03-18
Otwarcie           24.35
Zamkniecie          24.4
Wolumen            12905
Name: 550, dtype: object

551 Data          2019-03-19
Otwarcie           24.45
Zamkniecie         24.75
Wolumen            25108
Name: 551, dtype: object
552 Data          2019-03-20
Otwarcie            24.7
Zamkniecie         26.85
Wolumen            25715
Name: 552, dtype: object
553 Data          2019-03-21
Otwarcie            26.8
Zamkniecie         28.05
Wolumen            81211
Name: 553, dtype: object
554 Data          2019-03-22
Otwarcie            28.1
Zamkniecie         27.35
Wolumen            24205
Name: 554, dtype: object
555 Data          2019-03-25
Otwarcie            27.1
Zamkniecie          26.7
Wolumen            10696
Name: 555, dtype: object
556 Data          2019-03-26
Otwarcie              27
Zamkniecie            28
Wolumen            14766
Name: 556, dtype: object
557 Data          2019-03-27
Otwarcie           28.15
Zamkniecie          26.6
Wolumen            18022
Name: 557, dtype: object
558 Data          2019-03-28
Otwarcie            26.6
Zamkniecie          26.1
Wolumen            44429
Name: 558, dtype: object
559 Data          2019-03-29
Otwarcie           26.35
Zamkniecie          25.9
Wolumen            11652
Name: 559, dtype: object
560 Data          2019-04-01
Otwarcie           26.15
Zamkniecie          26.4
Wolumen            14774
Name: 560, dtype: object
561 Data          2019-04-02
Otwarcie              27
Zamkniecie         27.95
Wolumen            17724
Name: 561, dtype: object
562 Data          2019-04-03
Otwarcie            28.6
Zamkniecie          29.4
Wolumen            42813
Name: 562, dtype: object
563 Data          2019-04-04
Otwarcie            29.5
Zamkniecie          29.3
Wolumen            54442
Name: 563, dtype: object
564 Data          2019-04-05
Otwarcie            29.3
Zamkniecie          28.6
Wolumen            45406
Name: 564, dtype: object
565 Data          2019-04-08
Otwarcie           28.55
Zamkniecie         28.85
Wolumen             8171
Name: 565, dtype: object
566 Data          2019-04-09
Otwarcie            29.2
Zamkniecie          29.2
Wolumen            18135
Name: 566, dtype: object
567 Data          2019-04-10
Otwarcie           29.65
Zamkniecie         29.05
Wolumen             7375
Name: 567, dtype: object
568 Data          2019-04-11
Otwarcie            29.2
Zamkniecie          29.3
Wolumen             4317
Name: 568, dtype: object
569 Data          2019-04-12
Otwarcie           29.15
Zamkniecie         28.85
Wolumen            99781
Name: 569, dtype: object
570 Data          2019-04-15
Otwarcie           28.85
Zamkniecie          29.1
Wolumen             1932
Name: 570, dtype: object
571 Data          2019-04-16
Otwarcie            29.1
Zamkniecie         28.65
Wolumen             8167
Name: 571, dtype: object
572 Data          2019-04-17
Otwarcie           28.65
Zamkniecie          28.4
Wolumen             4118
Name: 572, dtype: object
573 Data          2019-04-18
Otwarcie           28.15
Zamkniecie          28.4
Wolumen             4199
Name: 573, dtype: object
574 Data          2019-04-23
Otwarcie            28.4
Zamkniecie          27.8
Wolumen            27439
Name: 574, dtype: object
575 Data          2019-04-24
Otwarcie              29
Zamkniecie         29.35
Wolumen            32943
Name: 575, dtype: object
576 Data          2019-04-25
Otwarcie            29.2
Zamkniecie          28.8
Wolumen            52923
Name: 576, dtype: object
577 Data          2019-04-26
Otwarcie              29
Zamkniecie         28.35
Wolumen             6838
Name: 577, dtype: object
578 Data          2019-04-29
Otwarcie            28.4
Zamkniecie         28.05
Wolumen             8187
Name: 578, dtype: object
579 Data          2019-04-30
Otwarcie           28.05
Zamkniecie          27.6
Wolumen            10398
Name: 579, dtype: object
580 Data          2019-05-02
Otwarcie           27.35
Zamkniecie         27.35
Wolumen            14970
Name: 580, dtype: object
581 Data          2019-05-06
Otwarcie            27.1
Zamkniecie          26.7
Wolumen            18797
Name: 581, dtype: object
582 Data          2019-05-07
Otwarcie            27.1
Zamkniecie          26.9
Wolumen            23246
Name: 582, dtype: object
583 Data          2019-05-08
Otwarcie           26.75
Zamkniecie            28
Wolumen            27073
Name: 583, dtype: object
584 Data          2019-05-09
Otwarcie            27.6
Zamkniecie         28.25
Wolumen            30500
Name: 584, dtype: object
585 Data          2019-05-10
Otwarcie           28.25
Zamkniecie          27.9
Wolumen            23207
Name: 585, dtype: object
586 Data          2019-05-13
Otwarcie            27.9
Zamkniecie         27.15
Wolumen             7771
Name: 586, dtype: object
587 Data          2019-05-14
Otwarcie            27.1
Zamkniecie          27.7
Wolumen             5835
Name: 587, dtype: object
588 Data          2019-05-15
Otwarcie              28
Zamkniecie          28.2
Wolumen            10134
Name: 588, dtype: object
589 Data          2019-05-16
Otwarcie           27.95
Zamkniecie          28.5
Wolumen            26746
Name: 589, dtype: object
590 Data          2019-05-17
Otwarcie            28.5
Zamkniecie          28.5
Wolumen             7071
Name: 590, dtype: object
591 Data          2019-05-20
Otwarcie           27.95
Zamkniecie          28.2
Wolumen             1359
Name: 591, dtype: object
592 Data          2019-05-21
Otwarcie            27.9
Zamkniecie         28.55
Wolumen             7354
Name: 592, dtype: object
593 Data          2019-05-22
Otwarcie            28.4
Zamkniecie          28.6
Wolumen             3383
Name: 593, dtype: object
594 Data          2019-05-23
Otwarcie           28.85
Zamkniecie         29.15
Wolumen            16602
Name: 594, dtype: object
595 Data          2019-05-24
Otwarcie           29.75
Zamkniecie         29.65
Wolumen            22503
Name: 595, dtype: object
596 Data          2019-05-27
Otwarcie           29.65
Zamkniecie          30.7
Wolumen            21936
Name: 596, dtype: object
597 Data          2019-05-28
Otwarcie              31
Zamkniecie          31.5
Wolumen            10665
Name: 597, dtype: object
598 Data          2019-05-29
Otwarcie              32
Zamkniecie          30.6
Wolumen             8034
Name: 598, dtype: object
599 Data          2019-05-30
Otwarcie           30.65
Zamkniecie         30.25
Wolumen            35480
Name: 599, dtype: object
600 Data          2019-05-31
Otwarcie           30.15
Zamkniecie         29.75
Wolumen            22738
Name: 600, dtype: object
601 Data          2019-06-03
Otwarcie            29.8
Zamkniecie            30
Wolumen            11295
Name: 601, dtype: object
602 Data          2019-06-04
Otwarcie            30.1
Zamkniecie          29.5
Wolumen             7612
Name: 602, dtype: object
603 Data          2019-06-05
Otwarcie            29.5
Zamkniecie         29.75
Wolumen             5461
Name: 603, dtype: object
604 Data          2019-06-06
Otwarcie           29.75
Zamkniecie          29.8
Wolumen             7343
Name: 604, dtype: object
605 Data          2019-06-07
Otwarcie           29.75
Zamkniecie          29.5
Wolumen             4622
Name: 605, dtype: object
606 Data          2019-06-10
Otwarcie            29.5
Zamkniecie         29.45
Wolumen             4549
Name: 606, dtype: object
607 Data          2019-06-11
Otwarcie              30
Zamkniecie         29.75
Wolumen             4571
Name: 607, dtype: object
608 Data          2019-06-12
Otwarcie           29.75
Zamkniecie         29.95
Wolumen             2807
Name: 608, dtype: object
609 Data          2019-06-13
Otwarcie            30.6
Zamkniecie         29.75
Wolumen            12030
Name: 609, dtype: object
610 Data          2019-06-14
Otwarcie            29.8
Zamkniecie          29.9
Wolumen             7286
Name: 610, dtype: object
611 Data          2019-06-17
Otwarcie            29.9
Zamkniecie          29.9
Wolumen            91994
Name: 611, dtype: object
612 Data          2019-06-18
Otwarcie            30.6
Zamkniecie          30.6
Wolumen             9745
Name: 612, dtype: object
613 Data          2019-06-19
Otwarcie            30.5
Zamkniecie          30.7
Wolumen             3053
Name: 613, dtype: object
614 Data          2019-06-21
Otwarcie              31
Zamkniecie          30.1
Wolumen            11413
Name: 614, dtype: object
615 Data          2019-06-24
Otwarcie            30.4
Zamkniecie          30.1
Wolumen             2824
Name: 615, dtype: object
616 Data          2019-06-25
Otwarcie            30.4
Zamkniecie            30
Wolumen             3967
Name: 616, dtype: object
617 Data          2019-06-26
Otwarcie              30
Zamkniecie          29.9
Wolumen             2256
Name: 617, dtype: object
618 Data          2019-06-27
Otwarcie            29.9
Zamkniecie         29.95
Wolumen             3585
Name: 618, dtype: object
619 Data          2019-06-28
Otwarcie              30
Zamkniecie          29.9
Wolumen             3733
Name: 619, dtype: object
620 Data          2019-07-01
Otwarcie            29.9
Zamkniecie         30.55
Wolumen            12622
Name: 620, dtype: object
621 Data          2019-07-02
Otwarcie            30.6
Zamkniecie          30.5
Wolumen              848
Name: 621, dtype: object
622 Data          2019-07-03
Otwarcie           30.95
Zamkniecie          30.9
Wolumen             8389
Name: 622, dtype: object
623 Data          2019-07-04
Otwarcie           30.95
Zamkniecie         31.85
Wolumen             9875
Name: 623, dtype: object
624 Data          2019-07-05
Otwarcie              32
Zamkniecie            32
Wolumen            11295
Name: 624, dtype: object
625 Data          2019-07-08
Otwarcie           33.25
Zamkniecie         31.95
Wolumen            14768
Name: 625, dtype: object
626 Data          2019-07-09
Otwarcie              32
Zamkniecie          31.2
Wolumen           108514
Name: 626, dtype: object
627 Data          2019-07-10
Otwarcie            31.2
Zamkniecie         31.15
Wolumen           110320
Name: 627, dtype: object
628 Data          2019-07-11
Otwarcie              31
Zamkniecie          32.8
Wolumen             6762
Name: 628, dtype: object
629 Data          2019-07-12
Otwarcie            32.4
Zamkniecie          31.9
Wolumen            18057
Name: 629, dtype: object
630 Data          2019-07-15
Otwarcie            32.3
Zamkniecie          32.5
Wolumen             1186
Name: 630, dtype: object
631 Data          2019-07-16
Otwarcie            32.5
Zamkniecie         32.05
Wolumen             1527
Name: 631, dtype: object
632 Data          2019-07-17
Otwarcie              32
Zamkniecie         31.65
Wolumen             2443
Name: 632, dtype: object
633 Data          2019-07-18
Otwarcie           31.65
Zamkniecie            32
Wolumen              737
Name: 633, dtype: object
634 Data          2019-07-19
Otwarcie           32.55
Zamkniecie          32.6
Wolumen             4313
Name: 634, dtype: object

635 Data          2019-07-22
Otwarcie            32.8
Zamkniecie          32.9
Wolumen            32398
Name: 635, dtype: object
636 Data          2019-07-23
Otwarcie              33
Zamkniecie         32.75
Wolumen             2417
Name: 636, dtype: object
637 Data          2019-07-24
Otwarcie            32.9
Zamkniecie            32
Wolumen             3183
Name: 637, dtype: object
638 Data          2019-07-25
Otwarcie           29.95
Zamkniecie            28
Wolumen            81981
Name: 638, dtype: object
639 Data          2019-07-26
Otwarcie              28
Zamkniecie         24.85
Wolumen            73517
Name: 639, dtype: object
640 Data          2019-07-29
Otwarcie              24
Zamkniecie            25
Wolumen            17702
Name: 640, dtype: object
641 Data          2019-07-30
Otwarcie            25.1
Zamkniecie          25.5
Wolumen             2894
Name: 641, dtype: object
642 Data          2019-07-31
Otwarcie              27
Zamkniecie          26.5
Wolumen            17437
Name: 642, dtype: object
643 Data          2019-08-01
Otwarcie            26.5
Zamkniecie          26.1
Wolumen            11183
Name: 643, dtype: object
644 Data          2019-08-02
Otwarcie            26.2
Zamkniecie         26.55
Wolumen             3613
Name: 644, dtype: object
645 Data          2019-08-05
Otwarcie            26.6
Zamkniecie          25.8
Wolumen             3735
Name: 645, dtype: object
646 Data          2019-08-06
Otwarcie            25.8
Zamkniecie         26.05
Wolumen             4862
Name: 646, dtype: object
647 Data          2019-08-07
Otwarcie            25.9
Zamkniecie          26.1
Wolumen             4649
Name: 647, dtype: object
648 Data          2019-08-08
Otwarcie            26.4
Zamkniecie            26
Wolumen             5688
Name: 648, dtype: object
649 Data          2019-08-09
Otwarcie              26
Zamkniecie          26.5
Wolumen             3341
Name: 649, dtype: object
650 Data          2019-08-12
Otwarcie            26.1
Zamkniecie         25.95
Wolumen             1552
Name: 650, dtype: object
651 Data          2019-08-13
Otwarcie            25.1
Zamkniecie          25.4
Wolumen            11934
Name: 651, dtype: object
652 Data          2019-08-14
Otwarcie           25.55
Zamkniecie          25.2
Wolumen           134730
Name: 652, dtype: object
653 Data          2019-08-16
Otwarcie            25.2
Zamkniecie            25
Wolumen             4209
Name: 653, dtype: object
654 Data          2019-08-19
Otwarcie           24.65
Zamkniecie          25.2
Wolumen             3564
Name: 654, dtype: object
655 Data          2019-08-20
Otwarcie              25
Zamkniecie          24.9
Wolumen             2832
Name: 655, dtype: object
656 Data          2019-08-21
Otwarcie            24.2
Zamkniecie          24.8
Wolumen             1281
Name: 656, dtype: object
657 Data          2019-08-22
Otwarcie            24.8
Zamkniecie            25
Wolumen             4882
Name: 657, dtype: object
658 Data          2019-08-23
Otwarcie            25.3
Zamkniecie         24.85
Wolumen             6334
Name: 658, dtype: object
659 Data          2019-08-26
Otwarcie            24.1
Zamkniecie            25
Wolumen            13126
Name: 659, dtype: object
660 Data          2019-08-27
Otwarcie              25
Zamkniecie         24.95
Wolumen             8037
Name: 660, dtype: object
661 Data          2019-08-28
Otwarcie            25.2
Zamkniecie          24.3
Wolumen             1345
Name: 661, dtype: object
662 Data          2019-08-29
Otwarcie              25
Zamkniecie            25
Wolumen              977
Name: 662, dtype: object
663 Data          2019-08-30
Otwarcie           24.95
Zamkniecie            25
Wolumen             3335
Name: 663, dtype: object
664 Data          2019-09-02
Otwarcie              25
Zamkniecie            25
Wolumen              589
Name: 664, dtype: object

#### DataFrame.loc

In [91]:
print(df.loc[df['Otwarcie'] == 83.705])

          Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
51  2017-03-15    83.705     84.573     82.807      83.276    21202

In [109]:
df.describe()

         Otwarcie   Najwyzszy   Najnizszy  Zamkniecie        Wolumen
count  665.000000  665.000000  665.000000  665.000000     665.000000
mean    50.883014   51.543688   50.019734   50.767964   22189.634586
std     20.751097   20.877764   20.580506   20.771651   45087.041625
min     20.500000   21.000000   19.500000   20.350000     107.000000
25%     29.750000   30.000000   29.000000   29.500000    2832.000000
50%     49.900000   50.600000   48.900000   50.000000    7144.000000
75%     72.500000   72.970000   71.120000   72.480000   20029.000000
max     85.271000   85.779000   83.834000   85.231000  353461.000000

In [128]:
df.sort_values(['Otwarcie', 'Data'], ascending=[True, False])

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
477  2018-11-28    20.500     22.050     20.050      20.350   250151
472  2018-11-21    20.550     21.000     20.300      21.000    12929
478  2018-11-29    20.650     21.600     20.500      21.000    13779
474  2018-11-23    20.700     21.000     20.700      21.000    26154
470  2018-11-19    20.700     22.000     20.550      21.900   129388
480  2018-12-03    21.000     21.700     20.550      21.700    68783
479  2018-11-30    21.000     21.650     20.350      20.700    13647
475  2018-11-26    21.000     21.500     20.200      20.800    42155
473  2018-11-22    21.000     21.000     19.500      20.550    13781
471  2018-11-20    21.200     21.650     20.550      20.600    13173
476  2018-11-27    21.500     21.500     19.620      20.700    77268
492  2018-12-19    21.900     22.700     21.900      22.450    71883
482  2018-12-05    21.950     24.450     21.750      23.950    51980
507  2019-01-16    22.000     22.500     21.250      22.400    11917
481  2018-12-04    22.000     23.200     21.350      22.500   353461
467  2018-11-14    22.000     22.900     22.000      22.900     2385
546  2019-03-12    22.300     22.350     21.100      22.250    98805
547  2019-03-13    22.350     22.500     22.000      22.500     9966
508  2019-01-17    22.400     22.700     22.200      22.600     5746
496  2018-12-28    22.450     22.850     22.450      22.750     5059
494  2018-12-21    22.450     22.700     22.450      22.500    24989
493  2018-12-20    22.450     23.100     22.450      22.650    41918
502  2019-01-09    22.500     22.750     22.300      22.500     7142
491  2018-12-18    22.500     22.700     21.800      22.100    23802
468  2018-11-15    22.500     24.400     22.400      22.900    38548
506  2019-01-15    22.550     22.850     21.900      22.000    19106
510  2019-01-21    22.700     23.350     22.550      23.350    24382
509  2019-01-18    22.700     22.750     22.400      22.600    33823
503  2019-01-10    22.700     23.000     22.400      22.600    17776
466  2018-11-13    22.700     22.700     21.250      22.000   107495
..          ...       ...        ...        ...         ...      ...
122  2017-06-29    82.500     82.500     80.700      81.500     7370
22   2017-02-02    82.687     82.737     81.540      82.079     2421
129  2017-07-10    82.710     82.710     81.500      81.500      398
46   2017-03-08    82.787     83.086     80.812      81.181    14775
30   2017-02-14    82.787     82.787     81.341      81.780     2057
20   2017-01-31    82.787     84.573     81.301      82.787    11637
21   2017-02-01    82.797     83.635     81.860      82.777     7932
32   2017-02-16    82.877     82.987     79.725      81.780    10659
125  2017-07-04    82.950     82.950     80.000      80.000     1196
23   2017-02-03    82.987     82.987     80.992      81.291     3901
55   2017-03-21    83.286     83.286     80.314      81.790    25528
53   2017-03-17    83.286     83.286     83.166      83.206     9920
52   2017-03-16    83.286     83.286     83.086      83.286     3212
77   2017-04-24    83.416     83.416     81.989      82.787     3108
121  2017-06-28    83.500     83.500     82.400      82.430      707
41   2017-03-01    83.685     83.685     83.346      83.685     5695
39   2017-02-27    83.685     84.383     82.169      83.066     4584
42   2017-03-02    83.695     85.779     82.797      85.171     6031
51   2017-03-15    83.705     84.573     82.807      83.276    21202
54   2017-03-20    83.755     84.573     82.787      82.787    50197
49   2017-03-13    83.775     84.283     82.029      83.585    20527
38   2017-02-24    83.775     84.383     82.388      84.383     3470
37   2017-02-23    83.785     83.785     82.398      83.685     2255
29   2017-02-13    83.785     83.785     82.777      82.787     1546
28   2017-02-10    83.785     84.283     83.386      83.685     1321
45   2017-03-07    84.263     84.383     82.298      82.787    15403
43   2017-03-03    84.383     85.281     83.805      85.231     2725
17   2017-01-26    84.583     85.779     82.588      83.785    17243
50   2017-03-14    84.692     84.692     83.037      83.705    21007
44   2017-03-06    85.271     85.271     83.834      84.423      707

[665 rows x 6 columns]