In [208]:
import pandas as pd
df = pd.read_csv('fte.csv')
print(df.head(5))

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971
3  2017-01-05    75.705     75.805     73.312      73.511    19547
4  2017-01-09    73.790     75.197     72.414      72.813    14825

In [14]:
print(df.tail())

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
660  2019-08-27     25.00      25.20       24.5       24.95     8037
661  2019-08-28     25.20      25.20       24.3       24.30     1345
662  2019-08-29     25.00      25.00       24.2       25.00      977
663  2019-08-30     24.95      25.00       24.4       25.00     3335
664  2019-09-02     25.00      25.15       24.7       25.00      589

In [15]:
len(df)

665

In [20]:
df_xls = pd.read_excel('fte.xls')
df.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [23]:
df_xlsx = pd.read_excel('fte.xlsx')
df.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [25]:
df_txt = pd.read_csv('fte.txt')
df_txt.head(3)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971

In [31]:
print(df.columns)

Index(['Data', 'Otwarcie', 'Najwyzszy', 'Najnizszy', 'Zamkniecie', 'Wolumen'], dtype='object')

In [43]:
print(df[['Data', 'Otwarcie', 'Zamkniecie']].head(3))

         Data  Otwarcie  Zamkniecie
0  2017-01-02    74.858      77.102
1  2017-01-03    77.800      76.503
2  2017-01-04    76.603      75.606

In [42]:
print(df.Data.head(3))

0    2017-01-02
1    2017-01-03
2    2017-01-04
Name: Data, dtype: object

In [52]:
print(df.iloc[22:33])

          Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
22  2017-02-02    82.687     82.737     81.540      82.079     2421
23  2017-02-03    82.987     82.987     80.992      81.291     3901
24  2017-02-06    81.750     83.475     81.291      81.291     3566
25  2017-02-07    81.491     81.491     78.957      79.845     5071
26  2017-02-08    79.765     81.281     78.897      81.281     4911
27  2017-02-09    81.281     84.952     80.124      83.785     8658
28  2017-02-10    83.785     84.283     83.386      83.685     1321
29  2017-02-13    83.785     83.785     82.777      82.787     1546
30  2017-02-14    82.787     82.787     81.341      81.780     2057
31  2017-02-15    82.039     82.189     81.301      81.870     2672
32  2017-02-16    82.877     82.987     79.725      81.780    10659

In [59]:
print(df.iloc[22:25,3:5])

    Najnizszy  Zamkniecie
22     81.540      82.079
23     80.992      81.291
24     81.291      81.291

#### DataFrame.iterrows

In [1]:
# for a, b in df.iterrows():
#     print(a, b[['Data', 'Otwarcie', 'Zamkniecie', 'Wolumen']])

#### DataFrame.loc

In [137]:
print(df.loc[df['Otwarcie'] == 83.705].head(5))

          Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
51  2017-03-15    83.705     84.573     82.807      83.276    21202

In [143]:
df.describe()

         Otwarcie   Najwyzszy   Najnizszy  Zamkniecie        Wolumen
count  665.000000  665.000000  665.000000  665.000000     665.000000
mean    50.883014   51.543688   50.019734   50.767964   22189.634586
std     20.751097   20.877764   20.580506   20.771651   45087.041625
min     20.500000   21.000000   19.500000   20.350000     107.000000
25%     29.750000   30.000000   29.000000   29.500000    2832.000000
50%     49.900000   50.600000   48.900000   50.000000    7144.000000
75%     72.500000   72.970000   71.120000   72.480000   20029.000000
max     85.271000   85.779000   83.834000   85.231000  353461.000000

In [165]:
df.sort_values(['Otwarcie', 'Data'], ascending=[True, 0]).head(6)

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen  Srednia
477  2018-11-28     20.50      22.05      20.05       20.35   250151   21.050
472  2018-11-21     20.55      21.00      20.30       21.00    12929   20.650
478  2018-11-29     20.65      21.60      20.50       21.00    13779   21.050
474  2018-11-23     20.70      21.00      20.70       21.00    26154   20.850
470  2018-11-19     20.70      22.00      20.55       21.90   129388   21.275
480  2018-12-03     21.00      21.70      20.55       21.70    68783   21.125

In [6]:
df['Srednia'] = (df['Najwyzszy'] + df['Najnizszy']) / 2

In [7]:
df.head(5)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen  Srednia
0  2017-01-02    74.858     77.102     73.810      77.102    14020  75.4560
1  2017-01-03    77.800     77.900     76.503      76.503     2055  77.2015
2  2017-01-04    76.603     76.703     75.606      75.606     2971  76.1545
3  2017-01-05    75.705     75.805     73.312      73.511    19547  74.5585
4  2017-01-09    73.790     75.197     72.414      72.813    14825  73.8055

In [8]:
df.drop(columns=['Srednia']).head(4)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2017-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971
3  2017-01-05    75.705     75.805     73.312      73.511    19547

In [9]:
df.drop(index=2).head(4)

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen  Srednia
0  2017-01-02    74.858     77.102     73.810      77.102    14020  75.4560
1  2017-01-03    77.800     77.900     76.503      76.503     2055  77.2015
3  2017-01-05    75.705     75.805     73.312      73.511    19547  74.5585
4  2017-01-09    73.790     75.197     72.414      72.813    14825  73.8055

In [21]:
srednia_por = df['Srednia_por'] = df.iloc[:, 2:4].mean(axis=1)
df.head(5)

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
0,2017-01-02,74.858,77.102,73.810,77.102,14020,75.4560,75.4560
1,2017-01-03,77.800,77.900,76.503,76.503,2055,77.2015,77.2015
2,2017-01-04,76.603,76.703,75.606,75.606,2971,76.1545,76.1545
3,2017-01-05,75.705,75.805,73.312,73.511,19547,74.5585,74.5585
4,2017-01-09,73.790,75.197,72.414,72.813,14825,73.8055,73.8055

In [22]:
df.columns

Index(['Data', 'Otwarcie', 'Najwyzszy', 'Najnizszy', 'Zamkniecie', 'Wolumen',
       'Srednia', 'Srednia_por'],
      dtype='object')

In [25]:
cols = list(df.columns)
cols

['Data',
 'Otwarcie',
 'Najwyzszy',
 'Najnizszy',
 'Zamkniecie',
 'Wolumen',
 'Srednia',
 'Srednia_por']

In [47]:
new_df = df[cols[:4] + [cols[-2]] + cols[4:6] + [cols[-1]]]

new_df.head(5)

,Data,Otwarcie,Najwyzszy,Najnizszy,Srednia,Zamkniecie,Wolumen,Srednia_por
0,2017-01-02,74.858,77.102,73.810,75.4560,77.102,14020,75.4560
1,2017-01-03,77.800,77.900,76.503,77.2015,76.503,2055,77.2015
2,2017-01-04,76.603,76.703,75.606,76.1545,75.606,2971,76.1545
3,2017-01-05,75.705,75.805,73.312,74.5585,73.511,19547,74.5585
4,2017-01-09,73.790,75.197,72.414,73.8055,72.813,14825,73.8055

In [55]:
new_df.to_csv('modified.csv', index=False)

In [56]:
new_df.to_excel('modified.xlsx', index=False)

In [58]:
new_df.to_csv('modified.txt', index=False, sep='\t')

In [64]:
a = pd.read_csv('modified.txt', delimiter= "\t")

## Filtrowanie

In [94]:
a = df['Otwarcie'] == 25 
b = df['Data'] == '2019-08-20'

In [102]:
df.loc[a & b]

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
655,2019-08-20,25.0,25.2,24.35,24.9,2832,24.775,24.775

In [109]:
df.loc[(df['Otwarcie'] == 25) & (df['Data'] == '2019-08-20')]

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
655,2019-08-20,25.0,25.2,24.35,24.9,2832,24.775,24.775

In [193]:
df.loc[~(df['Otwarcie'] < 25) & (df['Data'] == '2019-08-20')]  # wartiści spoza obszaru ~

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
655,2019-08-20,25.0,25.2,24.35,24.9,2832,24.775,24.775

In [184]:
filtered = df.loc[(df['Otwarcie'] == 25) | (df['Data'] == '2019-08-20')]
filtered

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
458,2018-10-30,25.0,26.85,24.25,25.60,167188,25.550,25.550
462,2018-11-06,25.0,25.45,23.95,23.95,316266,24.700,24.700
655,2019-08-20,25.0,25.20,24.35,24.90,2832,24.775,24.775
660,2019-08-27,25.0,25.20,24.50,24.95,8037,24.850,24.850
662,2019-08-29,25.0,25.00,24.20,25.00,977,24.600,24.600
664,2019-09-02,25.0,25.15,24.70,25.00,589,24.925,24.925

In [185]:
filtered = filtered.reset_index(drop=True)
filtered

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
0,2018-10-30,25.0,26.85,24.25,25.60,167188,25.550,25.550
1,2018-11-06,25.0,25.45,23.95,23.95,316266,24.700,24.700
2,2019-08-20,25.0,25.20,24.35,24.90,2832,24.775,24.775
3,2019-08-27,25.0,25.20,24.50,24.95,8037,24.850,24.850
4,2019-08-29,25.0,25.00,24.20,25.00,977,24.600,24.600
5,2019-09-02,25.0,25.15,24.70,25.00,589,24.925,24.925

In [186]:
df.loc[(df['Otwarcie'] != 25) & (df['Data'] > '2019-08-20') & (df['Wolumen'] > 10000)]

,Data,Otwarcie,Najwyzszy,Najnizszy,Zamkniecie,Wolumen,Srednia,Srednia_por
659,2019-08-26,24.1,25.45,24.1,25.0,13126,24.775,24.775

In [196]:
# df.loc[df['Nazwa kolumny'].str.contains('Wybrane_słowo')]  --> aby wyfiltrować rekordy z wybranym słowem w kolumnie


#Przykład z użyciem regex:
# import re
# df.loc[df['Nazwa kolumny'].str.contains('Wybrane_słowo| Drugie wybrane słowo', flags=re.I, regex=True)]
# df.loc[df['Nazwa kolumny'].str.contains('^sło[a-z]', flags=re.I, regex=True)]

### Zmiany warunkowe

In [222]:
df.loc[df['Data'] == '2017-01-02', 'Data'] = '2022-01-02'
war = df
war.head()

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  2022-01-02    74.858     77.102     73.810      77.102    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971
3  2017-01-05    75.705     75.805     73.312      73.511    19547
4  2017-01-09    73.790     75.197     72.414      72.813    14825

In [229]:
war.loc[war['Wolumen'] > 14000, ['Data', 'Zamkniecie']] = ['BRAK SESJI', 'TEST VALUE']
war.head()

         Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0  BRAK SESJI    74.858     77.102     73.810  TEST VALUE    14020
1  2017-01-03    77.800     77.900     76.503      76.503     2055
2  2017-01-04    76.603     76.703     75.606      75.606     2971
3  BRAK SESJI    75.705     75.805     73.312  TEST VALUE    19547
4  BRAK SESJI    73.790     75.197     72.414  TEST VALUE    14825

### Grupowanie

In [234]:
df.groupby(['Data']).mean()
df.groupby(['Data']).mean().sort_values('Wolumen', ascending=False).head()

             Otwarcie  Najwyzszy  Najnizszy       Wolumen
Data
BRAK SESJI  45.666853  46.520118  44.594275  59228.127962
2019-02-13  25.100000  25.100000  23.800000  13796.000000
2018-11-22  21.000000  21.000000  19.500000  13781.000000
2018-11-29  20.650000  21.600000  20.500000  13779.000000
2018-12-17  22.900000  23.800000  22.250000  13764.000000

In [236]:
df.groupby(['Data']).sum().sort_values('Wolumen', ascending=False).head()

            Otwarcie  Najwyzszy  Najnizszy   Wolumen
Data
BRAK SESJI  9635.706   9815.745   9409.392  12497135
2019-02-13    25.100     25.100     23.800     13796
2018-11-22    21.000     21.000     19.500     13781
2018-11-29    20.650     21.600     20.500     13779
2018-12-17    22.900     23.800     22.250     13764

In [239]:
countt = df.groupby(['Data']).count().sort_values('Wolumen', ascending=False).head()
countt

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
Data
BRAK SESJI       211        211        211         211      211
2018-07-23         1          1          1           1        1
2018-09-18         1          1          1           1        1
2018-09-17         1          1          1           1        1
2018-09-13         1          1          1           1        1

In [240]:
countt = df.groupby(['Data', 'Otwarcie']).count().sort_values('Wolumen', ascending=False).head()
countt

                     Najwyzszy  Najnizszy  Zamkniecie  Wolumen
Data       Otwarcie
BRAK SESJI 22.7              4          4           4        4
           27.0              3          3           3        3
           24.0              3          3           3        3
           45.0              3          3           3        3
           47.0              3          3           3        3

### Working with Big data (np. 20 GB file)

In [246]:
for df in pd.read_csv('modified.csv', chunksize=5):
    print('Wymiary:', df.shape)
    print(df)

Wymiary: (5, 8)
         Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
0  2017-01-02    74.858     77.102     73.810  75.4560      77.102    14020
1  2017-01-03    77.800     77.900     76.503  77.2015      76.503     2055
2  2017-01-04    76.603     76.703     75.606  76.1545      75.606     2971
3  2017-01-05    75.705     75.805     73.312  74.5585      73.511    19547
4  2017-01-09    73.790     75.197     72.414  73.8055      72.813    14825

   Srednia_por
0      75.4560
1      77.2015
2      76.1545
3      74.5585
4      73.8055
Wymiary: (5, 8)
         Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
5  2017-01-10    72.813     75.705     72.813  74.2590      73.411    93285
6  2017-01-11    73.411     74.808     73.411  74.1095      74.618     3876
7  2017-01-12    74.618     74.618     74.199  74.4085      74.199      927
8  2017-01-13    73.810     74.070     72.813  73.4415      74.070    20616
9  2017-01-16    74.070     74.608     73.411  74.0095      74.608     2568

   Srednia_por
5      74.2590
6      74.1095
7      74.4085
8      73.4415
9      74.0095
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
10  2017-01-17    74.558     75.795     73.870  74.8325      75.486     2552
11  2017-01-18    75.606     76.803     75.027  75.9150      76.473     7508
12  2017-01-19    76.404     76.404     75.456  75.9300      75.805    17281
13  2017-01-20    76.104     76.603     75.306  75.9545      76.533    12876
14  2017-01-23    77.202     77.202     75.915  76.5585      76.902     5484

    Srednia_por
10      74.8325
11      75.9150
12      75.9300
13      75.9545
14      76.5585
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
15  2017-01-24    76.603     77.202     76.603  76.9025      76.703    13639
16  2017-01-25    78.997     82.578     78.997  80.7875      80.992    20593
17  2017-01-26    84.583     85.779     82.588  84.1835      83.785    17243
18  2017-01-27    81.889     83.086     81.062  82.0740      81.371     5751
19  2017-01-30    81.281     82.787     81.062  81.9245      82.787     4636

    Srednia_por
15      76.9025
16      80.7875
17      84.1835
18      82.0740
19      81.9245
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
20  2017-01-31    82.787     84.573     81.301  82.9370      82.787    11637
21  2017-02-01    82.797     83.635     81.860  82.7475      82.777     7932
22  2017-02-02    82.687     82.737     81.540  82.1385      82.079     2421
23  2017-02-03    82.987     82.987     80.992  81.9895      81.291     3901
24  2017-02-06    81.750     83.475     81.291  82.3830      81.291     3566

    Srednia_por
20      82.9370
21      82.7475
22      82.1385
23      81.9895
24      82.3830
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
25  2017-02-07    81.491     81.491     78.957  80.2240      79.845     5071
26  2017-02-08    79.765     81.281     78.897  80.0890      81.281     4911
27  2017-02-09    81.281     84.952     80.124  82.5380      83.785     8658
28  2017-02-10    83.785     84.283     83.386  83.8345      83.685     1321
29  2017-02-13    83.785     83.785     82.777  83.2810      82.787     1546

    Srednia_por
25      80.2240
26      80.0890
27      82.5380
28      83.8345
29      83.2810
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
30  2017-02-14    82.787     82.787     81.341  82.0640      81.780     2057
31  2017-02-15    82.039     82.189     81.301  81.7450      81.870     2672
32  2017-02-16    82.877     82.987     79.725  81.3560      81.780    10659
33  2017-02-17    82.388     82.388     80.792  81.5900      80.792     4819
34  2017-02-20    81.092     83.785     79.964  81.8745      80.982    18356

    Srednia_por
30      82.0640
31      81.7450
32      81.3560
33      81.5900
34      81.8745
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
35  2017-02-21    80.792     81.131     80.024  80.5775      80.992     8408
36  2017-02-22    80.982     82.288     80.792  81.5400      82.288     2884
37  2017-02-23    83.785     83.785     82.398  83.0915      83.685     2255
38  2017-02-24    83.775     84.383     82.388  83.3855      84.383     3470
39  2017-02-27    83.685     84.383     82.169  83.2760      83.066     4584

    Srednia_por
35      80.5775
36      81.5400
37      83.0915
38      83.3855
39      83.2760
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
40  2017-02-28    82.288     83.785     82.288  83.0365      83.785     3595
41  2017-03-01    83.685     83.685     83.346  83.5155      83.685     5695
42  2017-03-02    83.695     85.779     82.797  84.2880      85.171     6031
43  2017-03-03    84.383     85.281     83.805  84.5430      85.231     2725
44  2017-03-06    85.271     85.271     83.834  84.5525      84.423      707

    Srednia_por
40      83.0365
41      83.5155
42      84.2880
43      84.5430
44      84.5525
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
45  2017-03-07    84.263     84.383     82.298  83.3405      82.787    15403
46  2017-03-08    82.787     83.086     80.812  81.9490      81.181    14775
47  2017-03-09    81.062     81.062     77.930  79.4960      78.827     6027
48  2017-03-10    78.847     83.785     78.847  81.3160      81.151     5952
49  2017-03-13    83.775     84.283     82.029  83.1560      83.585    20527

    Srednia_por
45      83.3405
46      81.9490
47      79.4960
48      81.3160
49      83.1560
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
50  2017-03-14    84.692     84.692     83.037  83.8645      83.705    21007
51  2017-03-15    83.705     84.573     82.807  83.6900      83.276    21202
52  2017-03-16    83.286     83.286     83.086  83.1860      83.286     3212
53  2017-03-17    83.286     83.286     83.166  83.2260      83.206     9920
54  2017-03-20    83.755     84.573     82.787  83.6800      82.787    50197

    Srednia_por
50      83.8645
51      83.6900
52      83.1860
53      83.2260
54      83.6800
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
55  2017-03-21    83.286     83.286     80.314  81.8000      81.790    25528
56  2017-03-22    81.790     81.790     79.845  80.8175      81.291     4856
57  2017-03-23    81.790     81.790     80.314  81.0520      81.291     5464
58  2017-03-24    80.792     81.291     79.785  80.5380      80.772     1978
59  2017-03-27    78.807     79.595     78.807  79.2010      79.396     1973

    Srednia_por
55      81.8000
56      80.8175
57      81.0520
58      80.5380
59      79.2010
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
60  2017-03-28    79.396     81.650     79.396  80.5230      79.496     1775
61  2017-03-29    79.795     81.540     79.795  80.6675      80.543     3451
62  2017-03-30    79.795     81.082     79.795  80.4385      80.792     9138
63  2017-03-31    79.845     82.139     79.845  80.9920      81.840     2114
64  2017-04-03    81.570     81.800     80.752  81.2760      81.800      945

    Srednia_por
60      80.5230
61      80.6675
62      80.4385
63      80.9920
64      81.2760
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
65  2017-04-04    79.964     81.231     79.007  80.1190      79.795     2534
66  2017-04-05    79.805     82.139     79.805  80.9720      80.792     4662
67  2017-04-06    80.523     81.331     80.294  80.8125      80.792     1007
68  2017-04-07    81.181     81.790     80.363  81.0765      81.790     3507
69  2017-04-10    80.792     81.590     79.097  80.3435      79.097     3509

    Srednia_por
65      80.1190
66      80.9720
67      80.8125
68      81.0765
69      80.3435
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
70  2017-04-11    79.107     80.992     77.591  79.2915      77.591     3160
71  2017-04-12    77.780     79.286     77.780  78.5330      78.259     4670
72  2017-04-13    78.289     79.585     78.289  78.9370      79.585     1048
73  2017-04-18    78.448     79.486     78.448  78.9670      79.286     1598
74  2017-04-19    78.289     79.236     77.930  78.5830      78.289     8366

    Srednia_por
70      79.2915
71      78.5330
72      78.9370
73      78.9670
74      78.5830
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
75  2017-04-20    78.249     79.745     77.810  78.7775      79.745     3364
76  2017-04-21    79.795     83.575     79.795  81.6850      81.760    30718
77  2017-04-24    83.416     83.416     81.989  82.7025      82.787     3108
78  2017-04-25    81.291     81.790     76.104  78.9470      81.790   231416
79  2017-04-26    81.790     81.790     78.129  79.9595      78.777    16210

    Srednia_por
75      78.7775
76      81.6850
77      82.7025
78      78.9470
79      79.9595
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
80  2017-04-27    78.997     80.782     78.408  79.5950      79.097    38783
81  2017-04-28    79.097     80.463     78.398  79.4305      79.047     6401
82  2017-05-02    79.795     81.560     79.795  80.6775      81.560     8792
83  2017-05-04    81.291     81.780     79.675  80.7275      79.675     2514
84  2017-05-05    80.443     80.443     78.797  79.6200      79.276     2789

    Srednia_por
80      79.5950
81      79.4305
82      80.6775
83      80.7275
84      79.6200
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
85  2017-05-08    79.037     80.294     78.698  79.4960      78.797     1310
86  2017-05-09    78.897     79.735     76.603  78.1690      77.800     6354
87  2017-05-10    78.578     78.578     77.142  77.8600      77.561    30816
88  2017-05-11    77.561     77.700     75.805  76.7525      77.301     4038
89  2017-05-12    77.800     78.299     76.663  77.4810      76.982    56737

    Srednia_por
85      79.4960
86      78.1690
87      77.8600
88      76.7525
89      77.4810
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
90  2017-05-15    76.803     77.102     75.955  76.5285      76.214     3442
91  2017-05-16    75.875     76.803     75.875  76.3390      75.955     7420
92  2017-05-17    75.805     77.002     75.356  76.1790      77.002     4513
93  2017-05-18    77.002     78.797     75.825  77.3110      78.797     6102
94  2017-05-19    77.620     78.279     77.431  77.8550      77.431      842

    Srednia_por
90      76.5285
91      76.3390
92      76.1790
93      77.3110
94      77.8550
Wymiary: (5, 8)
          Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
95  2017-05-22   77.4310    79.5950     77.351  78.4730      79.595     1884
96  2017-05-23   79.5954    79.5954     77.401  78.4982      77.800     1041
97  2017-05-24   78.0000    79.7500     76.800  78.2750      79.450    21106
98  2017-05-25   79.3000    79.3000     78.200  78.7500      79.190     4692
99  2017-05-26   79.7500    79.7500     78.300  79.0250      78.500      989

    Srednia_por
95      78.4730
96      78.4982
97      78.2750
98      78.7500
99      79.0250
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
100  2017-05-29     78.50      78.61      77.29    77.95       77.40    81752
101  2017-05-30     77.50      77.64      76.70    77.17       77.45    91769
102  2017-05-31     77.00      78.00      76.82    77.41       78.00     6589
103  2017-06-01     77.50      77.69      75.75    76.72       76.50    34301
104  2017-06-02     77.45      78.99      76.85    77.92       76.85    36404

     Srednia_por
100        77.95
101        77.17
102        77.41
103        76.72
104        77.92
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
105  2017-06-05     76.15      77.01      76.15   76.580       76.90     6296
106  2017-06-06     76.21      76.88      76.21   76.545       76.88    53420
107  2017-06-07     76.88      77.20      76.50   76.850       76.60      690
108  2017-06-08     76.50      76.59      76.37   76.480       76.40      945
109  2017-06-09     76.50      76.90      76.50   76.700       76.90      859

     Srednia_por
105       76.580
106       76.545
107       76.850
108       76.480
109       76.700

Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
110  2017-06-12     76.90      76.90      76.51   76.705        76.9      663
111  2017-06-13     76.54      77.08      76.54   76.810        76.9      749
112  2017-06-14     76.66      77.00      75.99   76.495        77.0     3547
113  2017-06-16     76.61      78.50      76.60   77.550        78.5      533
114  2017-06-19     78.49      78.49      76.71   77.600        78.2      900

     Srednia_por
110       76.705
111       76.810
112       76.495
113       77.550
114       77.600
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
115  2017-06-20     78.32      79.69      78.30   78.995       79.64     2108
116  2017-06-21     79.69      79.69      78.95   79.320       79.35     2496
117  2017-06-22     79.05      80.45      78.71   79.580       79.69     2532
118  2017-06-23     79.99      80.01      79.55   79.780       80.00    21006
119  2017-06-26     80.75      81.50      80.50   81.000       81.48     3047

     Srednia_por
115       78.995
116       79.320
117       79.580
118       79.780
119       81.000
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
120  2017-06-27     81.49      83.50       80.5   82.000       83.50     6037
121  2017-06-28     83.50      83.50       82.4   82.950       82.43      707
122  2017-06-29     82.50      82.50       80.7   81.600       81.50     7370
123  2017-06-30     80.60      82.35       80.6   81.475       82.35     7554
124  2017-07-03     82.48      82.48       81.0   81.740       82.00     3584

     Srednia_por
120       82.000
121       82.950
122       81.600
123       81.475
124       81.740
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
125  2017-07-04     82.95      82.95      80.00   81.475       80.00     1196
126  2017-07-05     80.00      82.00      79.97   80.985       82.00    24720
127  2017-07-06     81.31      82.04      81.00   81.520       82.04     1002
128  2017-07-07     81.69      82.70      81.22   81.960       82.70     1738
129  2017-07-10     82.71      82.71      81.50   82.105       81.50      398

     Srednia_por
125       81.475
126       80.985
127       81.520
128       81.960
129       82.105
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
130  2017-07-11     82.00      82.00      80.39   81.195       80.91      585
131  2017-07-12     82.00      82.00      79.10   80.550       79.10     1412
132  2017-07-13     79.22      80.00      79.00   79.500       79.00     1344
133  2017-07-14     79.30      79.78      79.05   79.415       79.20      285
134  2017-07-17     79.40      80.38      79.40   79.890       79.71      212

     Srednia_por
130       81.195
131       80.550
132       79.500
133       79.415
134       79.890
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
135  2017-07-18     80.19      81.00      79.86   80.430       80.22     1242
136  2017-07-19     80.20      80.22      79.67   79.945       79.67      871
137  2017-07-20     79.01      79.77      76.97   78.370       77.20    14972
138  2017-07-21     78.15      78.15      76.50   77.325       76.60    18199
139  2017-07-24     76.60      76.94      76.43   76.685       76.55    19904

     Srednia_por
135       80.430
136       79.945
137       78.370
138       77.325
139       76.685
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
140  2017-07-25     76.64      79.40      76.35   77.875       77.50     4743
141  2017-07-26     77.81      78.69      75.66   77.175       77.94    23859
142  2017-07-27     78.39      78.39      76.50   77.445       78.00     4652
143  2017-07-28     78.19      78.23      77.01   77.620       77.98     3228
144  2017-07-31     72.73      73.39      67.17   70.280       67.77    81324

     Srednia_por
140       77.875
141       77.175
142       77.445
143       77.620
144       70.280
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
145  2017-08-01     68.00      68.00      65.10   66.550       65.30    35349
146  2017-08-02     65.30      66.76      65.30   66.030       66.00    67975
147  2017-08-03     66.70      67.45      66.40   66.925       67.45     3916
148  2017-08-04     67.45      68.50      67.42   67.960       68.49    22594
149  2017-08-07     68.90      69.00      68.50   68.750       68.50     1604

     Srednia_por
145       66.550
146       66.030
147       66.925
148       67.960
149       68.750
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
150  2017-08-08      68.5      68.89       68.0   68.445       68.59     1361
151  2017-08-09      68.4      68.40       67.5   67.950       68.00    12408
152  2017-08-10      68.0      71.00       68.0   69.500       70.00    32474
153  2017-08-11      72.0      72.30       70.0   71.150       70.60    16023
154  2017-08-14      70.7      71.93       70.0   70.965       70.70     1501

     Srednia_por
150       68.445
151       67.950
152       69.500
153       71.150
154       70.965
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
155  2017-08-16     71.00      71.79      70.81   71.300       70.83      742
156  2017-08-17     70.99      70.99      69.50   70.245       69.50     3523
157  2017-08-18     69.60      70.00      69.60   69.800       70.00     4372
158  2017-08-21     70.50      71.00      69.82   70.410       71.00    10037
159  2017-08-22     71.00      72.00      70.01   71.005       72.00     2978

     Srednia_por
155       71.300
156       70.245
157       69.800
158       70.410
159       71.005
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
160  2017-08-23     72.00      72.50      72.00   72.250       72.00      618
161  2017-08-24     71.00      73.40      70.50   71.950       73.40    63933
162  2017-08-25     73.00      73.00      71.07   72.035       71.07     1827
163  2017-08-28     70.55      73.37      70.00   71.685       73.37     7521
164  2017-08-29     73.00      73.00      71.62   72.310       72.99     6730

     Srednia_por
160       72.250
161       71.950
162       72.035
163       71.685
164       72.310
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
165  2017-08-30     72.95      74.70      72.06   73.380       74.02     7146
166  2017-08-31     74.02      77.10      73.41   75.255       76.00    10683
167  2017-09-01     77.50      77.78      75.01   76.395       75.01     7445
168  2017-09-04     74.45      74.45      73.52   73.985       74.45     1780
169  2017-09-05     73.52      73.94      72.30   73.120       73.10     1962

     Srednia_por
165       73.380
166       75.255
167       76.395
168       73.985
169       73.120
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
170  2017-09-06     72.06       72.5      71.74   72.120       72.50     3521
171  2017-09-07     72.50       72.5      71.00   71.750       72.50     1440
172  2017-09-08     71.70       73.4      70.81   72.105       72.45     3067
173  2017-09-11     72.50       72.5      71.12   71.810       71.98     2266
174  2017-09-12     71.90       71.9      70.71   71.305       71.32     5001

     Srednia_por
170       72.120
171       71.750
172       72.105
173       71.810
174       71.305
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
175  2017-09-13     71.70      71.70      70.13   70.915       70.13    57468
176  2017-09-14     70.13      70.13      67.52   68.825       67.59    45357
177  2017-09-15     67.60      72.10      67.45   69.775       72.10   283835
178  2017-09-18     72.50      72.50      70.03   71.265       71.00    37141
179  2017-09-19     69.15      71.00      69.15   70.075       71.00     3679

     Srednia_por
175       70.915
176       68.825
177       69.775
178       71.265
179       70.075
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
180  2017-09-20     70.51      71.00      69.81   70.405       71.00     2288
181  2017-09-21     71.50      71.50      69.82   70.660       70.90     2863
182  2017-09-22     70.90      71.00      69.51   70.255       71.00     5858
183  2017-09-25     70.60      71.51      70.41   70.960       70.58      681
184  2017-09-26     70.58      71.70      70.03   70.865       71.00     2136

     Srednia_por
180       70.405
181       70.660
182       70.255
183       70.960
184       70.865
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
185  2017-09-27     70.90      72.48      70.11   71.295       72.48    12314
186  2017-09-28     72.49      72.78      72.02   72.400       72.75     4534
187  2017-09-29     72.75      72.75      72.02   72.385       72.75     6967
188  2017-10-02     72.75      73.00      71.56   72.280       73.00     2642
189  2017-10-03     73.73      73.73      72.37   73.050       72.89      889

     Srednia_por
185       71.295
186       72.400
187       72.385
188       72.280
189       73.050
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
190  2017-10-04     72.89      73.49      72.00   72.745       73.22     1009
191  2017-10-05     73.11      73.11      71.45   72.280       72.89      953
192  2017-10-06     72.89      72.89      71.36   72.125       72.50     2349
193  2017-10-09     73.00      73.00      71.65   72.325       73.00     1804
194  2017-10-10     73.00      74.00      72.70   73.350       74.00     1812

     Srednia_por
190       72.745
191       72.280
192       72.125
193       72.325
194       73.350
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
195  2017-10-11     74.00      74.24      73.20   73.720       74.00     2566
196  2017-10-12     73.70      73.90      73.15   73.525       73.21      719
197  2017-10-13     72.81      72.95      72.02   72.485       72.44     1735
198  2017-10-16     74.25      74.25      72.06   73.155       72.97      330
199  2017-10-17     72.97      72.97      71.15   72.060       72.14     1855

     Srednia_por
195       73.720
196       73.525
197       72.485
198       73.155
199       72.060
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
200  2017-10-18     72.04      73.09      71.01   72.050       71.37     1548
201  2017-10-19     73.57      73.57      69.10   71.335       70.95     4840
202  2017-10-20     69.51      71.70      68.42   70.060       68.94     7140
203  2017-10-23     69.20      69.20      67.61   68.405       68.38     2963
204  2017-10-24     66.00      66.00      60.30   63.150       63.25   179561

     Srednia_por
200       72.050
201       71.335
202       70.060
203       68.405
204       63.150
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
205  2017-10-25     62.56      65.00      61.01   63.005       65.00    14087
206  2017-10-26     66.52      66.60      64.90   65.750       64.90     4076
207  2017-10-27     65.00      66.50      65.00   65.750       66.50      914
208  2017-10-30     66.50      67.40      66.31   66.855       66.76     1253
209  2017-10-31     67.34      67.34      65.31   66.325       66.52     1637

     Srednia_por
205       63.005
206       65.750
207       65.750
208       66.855
209       66.325
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
210  2017-11-02     66.40      66.40      64.60   65.500       64.65     2889
211  2017-11-03     64.65      65.00      63.05   64.025       63.25     1379
212  2017-11-06     63.25      64.34      61.70   63.020       62.16    25030
213  2017-11-07     62.00      63.39      62.00   62.695       62.00    35450
214  2017-11-08     62.00      62.00      61.15   61.575       61.89     1739

     Srednia_por
210       65.500
211       64.025
212       63.020
213       62.695
214       61.575
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
215  2017-11-09     61.15      62.39      60.00   61.195       60.42     2518
216  2017-11-10     60.00      61.79      58.06   59.925       61.50     6511
217  2017-11-13     61.50      61.80      60.75   61.275       61.40     1373
218  2017-11-14     61.40      61.40      59.99   60.695       61.35     1693
219  2017-11-15     60.45      61.30      59.42   60.360       61.30     6423

     Srednia_por
215       61.195
216       59.925
217       61.275
218       60.695
219       60.360

Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
220  2017-11-16     61.40      61.40      60.42   60.910       60.89     1439
221  2017-11-17     60.02      61.24      59.82   60.530       60.79     2915
222  2017-11-20     61.00      61.90      59.98   60.940       59.98     3796
223  2017-11-21     60.01      61.88      59.82   60.850       60.00     6472
224  2017-11-22     60.03      60.97      60.00   60.485       60.20     3749

     Srednia_por
220       60.910
221       60.530
222       60.940
223       60.850
224       60.485
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
225  2017-11-23     60.65      62.40      60.33   61.365       60.45   179620
226  2017-11-24     61.00      61.00      60.45   60.725       60.50     3873
227  2017-11-27     61.19      61.19      60.50   60.845       60.98    26756
228  2017-11-28     60.61      61.76      60.61   61.185       61.43     2249
229  2017-11-29     61.50      61.50      59.52   60.510       60.19    37810

     Srednia_por
225       61.365
226       60.725
227       60.845
228       61.185
229       60.510
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
230  2017-11-30     60.35      60.35      58.15   59.250       59.60    13752
231  2017-12-01     60.35      60.35      58.25   59.300       58.25     5834
232  2017-12-04     58.25      59.85      58.25   59.050       59.55      980
233  2017-12-05     59.55      60.20      58.55   59.375       58.60     1490
234  2017-12-06     57.99      57.99      52.25   55.120       53.50    76928

     Srednia_por
230       59.250
231       59.300
232       59.050
233       59.375
234       55.120
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
235  2017-12-07     53.10      56.89      53.00   54.945       54.05    38356
236  2017-12-08     54.05      55.60      53.50   54.550       55.00     8167
237  2017-12-11     55.00      55.50      54.61   55.055       55.25     3608
238  2017-12-12     54.76      55.58      53.15   54.365       54.95    11539
239  2017-12-13     53.81      55.48      53.60   54.540       54.10     1095

     Srednia_por
235       54.945
236       54.550
237       55.055
238       54.365
239       54.540
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
240  2017-12-14     53.25      54.10      52.48   53.290       52.48     5176
241  2017-12-15     52.48      52.48      51.42   51.950       51.70    42294
242  2017-12-18     51.45      51.50      48.60   50.050       50.00    12068
243  2017-12-19     49.48      50.80      49.48   50.140       50.00     2418
244  2017-12-20     50.20      50.20      48.41   49.305       48.41     1664

     Srednia_por
240       53.290
241       51.950
242       50.050
243       50.140
244       49.305
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
245  2017-12-21     47.89      48.20      46.80   47.500       46.80    36611
246  2017-12-22     46.80      46.80      46.12   46.460       46.40     7655
247  2017-12-27     47.20      47.20      46.11   46.655       46.50     4497
248  2017-12-28     47.47      48.39      46.64   47.515       47.77     2977
249  2017-12-29     47.86      50.00      47.86   48.930       50.00     5424

     Srednia_por
245       47.500
246       46.460
247       46.655
248       47.515
249       48.930
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
250  2018-01-03      52.9       52.9       48.5    50.70        50.1     8975
251  2018-01-04      49.8       53.3       49.8    51.55        50.8   106313
252  2018-01-05      52.1       52.1       50.8    51.45        50.8    23478
253  2018-01-08      51.0       52.9       50.9    51.90        51.0    53748
254  2018-01-09      51.5       52.4       50.9    51.65        52.2     5036

     Srednia_por
250        50.70
251        51.55
252        51.45
253        51.90
254        51.65
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
255  2018-01-10      52.7       52.9      51.60   52.250       51.80     2998
256  2018-01-11      52.5       52.5      51.70   52.100       52.00     3369
257  2018-01-12      51.7       52.0      50.90   51.450       50.90     3025
258  2018-01-15      51.2       51.6      49.55   50.575       49.65     8153
259  2018-01-16      49.6       49.8      47.20   48.500       48.75     6313

     Srednia_por
255       52.250
256       52.100
257       51.450
258       50.575
259       48.500
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
260  2018-01-17     48.75       50.0      48.75   49.375       50.00     5080
261  2018-01-18     49.95       52.7      49.95   51.325       50.70    26490
262  2018-01-19     51.00       51.6      50.70   51.150       50.70     1372
263  2018-01-22     51.00       51.5      50.90   51.200       50.90     9870
264  2018-01-23     51.00       51.6      49.70   50.650       49.85     4024

     Srednia_por
260       49.375
261       51.325
262       51.150
263       51.200
264       50.650
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
265  2018-01-24     49.80      50.00      48.85   49.425        50.0     5133
266  2018-01-25     49.40      50.90      48.90   49.900        48.9     5711
267  2018-01-26     50.00      50.00      47.90   48.950        49.1     5764
268  2018-01-29     49.15      50.00      48.65   49.325        49.5    18678
269  2018-01-30     49.50      49.95      48.50   49.225        48.5     2255

     Srednia_por
265       49.425
266       49.900
267       48.950
268       49.325
269       49.225
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
270  2018-01-31     48.55      49.60      48.55   49.075       48.75     2876
271  2018-02-01     47.00      47.00      42.50   44.750       43.00   342725
272  2018-02-02     43.00      43.50      41.00   42.250       42.00    59908
273  2018-02-05     41.50      42.75      40.50   41.625       42.50    15525
274  2018-02-06     41.00      41.80      40.40   41.100       41.00   160643

     Srednia_por
270       49.075
271       44.750
272       42.250
273       41.625
274       41.100
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
275  2018-02-07     41.80       42.5      41.25   41.875        41.7    35158
276  2018-02-08     42.00       47.6      41.65   44.625        47.2   163206
277  2018-02-09     47.30       50.9      45.20   48.050        50.0    40698
278  2018-02-12     49.95       50.8      48.05   49.425        50.1    20516
279  2018-02-13     50.40       52.7      50.10   51.400        52.1    13007

     Srednia_por
275       41.875
276       44.625
277       48.050
278       49.425
279       51.400
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
280  2018-02-14      51.6       52.8       51.5    52.15        52.8    12074
281  2018-02-15      52.9       55.0       52.9    53.95        54.6     7998
282  2018-02-16      54.8       54.8       53.0    53.90        53.7    11639
283  2018-02-19      53.6       55.0       53.0    54.00        54.2     8014
284  2018-02-20      54.4       54.5       52.7    53.60        53.9    13151

     Srednia_por
280        52.15
281        53.95
282        53.90
283        54.00
284        53.60
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
285  2018-02-21      52.0       53.3       52.0    52.65        53.0     7144
286  2018-02-22      52.2       54.0       52.0    53.00        54.0     8212
287  2018-02-23      54.5       54.5       52.3    53.40        54.4    24277
288  2018-02-26      53.4       55.0       53.0    54.00        55.0     7848
289  2018-02-27      55.0       55.5       54.0    54.75        55.5     8995

     Srednia_por
285        52.65
286        53.00
287        53.40
288        54.00
289        54.75
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
290  2018-02-28      55.0       56.0       54.5    55.25        55.5    13355
291  2018-03-01      54.1       55.0       54.0    54.50        54.7     3760
292  2018-03-02      54.0       55.0       53.3    54.15        55.0     1367
293  2018-03-05      53.7       54.4       53.6    54.00        53.6     1080
294  2018-03-06      53.6       56.5       53.6    55.05        55.6     5687

     Srednia_por
290        55.25
291        54.50
292        54.15
293        54.00
294        55.05
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
295  2018-03-07      56.2       57.0       55.2    56.10        56.1   338940
296  2018-03-08      56.5       57.0       55.6    56.30        56.3   156345
297  2018-03-09      55.7       57.0       55.7    56.35        57.0     3884
298  2018-03-12      56.7       57.0       56.0    56.50        56.8     2636
299  2018-03-13      56.7       57.0       55.6    56.30        55.6   263803

     Srednia_por
295        56.10
296        56.30
297        56.35
298        56.50
299        56.30
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
300  2018-03-14      55.3       55.3       53.4    54.35        53.5     2162
301  2018-03-15      53.3       53.3       50.9    52.10        53.0     7428
302  2018-03-16      53.2       55.5       53.0    54.25        54.5     3423
303  2018-03-19      55.5       55.5       53.2    54.35        53.2     1735
304  2018-03-20      53.5       54.8       53.0    53.90        54.8     1144

     Srednia_por
300        54.35
301        52.10
302        54.25
303        54.35
304        53.90
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
305  2018-03-21      54.8       55.3       54.6    54.95        55.3    52786
306  2018-03-22      55.0       57.7       54.6    56.15        54.6    16161
307  2018-03-23      53.9       54.2       53.6    53.90        54.0     1502
308  2018-03-26      54.1       54.3       54.0    54.15        54.0     4831
309  2018-03-27      54.3       54.3       51.3    52.80        54.3    12876

     Srednia_por
305        54.95
306        56.15
307        53.90
308        54.15
309        52.80
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
310  2018-03-28      53.0       54.0       52.1    53.05        54.0     2291
311  2018-03-29      53.9       53.9       52.5    53.20        53.5     1618
312  2018-04-03      53.0       53.0       51.0    52.00        52.4     8245
313  2018-04-04      52.8       53.5       52.4    52.95        53.5     2432
314  2018-04-05      53.3       53.9       51.4    52.65        53.0     5520

     Srednia_por
310        53.05
311        53.20
312        52.00
313        52.95
314        52.65
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
315  2018-04-06      53.0       57.0       52.9    54.95        57.0    20029
316  2018-04-09      57.0       57.1       55.2    56.15        55.2    45534
317  2018-04-10      55.1       55.5       54.3    54.90        55.0   105270
318  2018-04-11      55.0       55.0       54.0    54.50        54.0   106571
319  2018-04-12      53.4       53.9       53.0    53.45        53.0     6179

     Srednia_por
315        54.95
316        56.15
317        54.90
318        54.50
319        53.45
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
320  2018-04-13      53.1       53.9       52.7    53.30        53.6     2260
321  2018-04-16      53.7       54.9       53.2    54.05        53.2    12615
322  2018-04-17      53.7       53.7       53.0    53.35        53.0      437
323  2018-04-18      54.9       54.9       52.7    53.80        52.9      969
324  2018-04-19      52.7       53.3       51.5    52.40        51.6    51704

     Srednia_por
320        53.30
321        54.05
322        53.35
323        53.80
324        52.40
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
325  2018-04-20      51.6       51.6       50.1    50.85        50.5    35471
326  2018-04-23      50.4       50.5       50.1    50.30        50.5     8144
327  2018-04-24      51.0       51.0       50.0    50.50        50.0    12780
328  2018-04-25      50.0       51.0       50.0    50.50        51.0      918
329  2018-04-26      51.0       52.2       50.0    51.10        50.7   138973

     Srednia_por
325        50.85
326        50.30
327        50.50
328        50.50
329        51.10
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
330  2018-04-27      52.7       52.7      50.60   51.650        50.6     2815
331  2018-04-30      50.6       50.6      50.20   50.400        50.2      575
332  2018-05-02      49.9       50.3      48.65   49.475        50.2     2802
333  2018-05-04      50.5       50.8      50.00   50.400        50.1     5270
334  2018-05-07      50.0       50.7      49.00   49.850        49.5    52803

     Srednia_por
330       51.650
331       50.400
332       49.475
333       50.400
334       49.850
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
335  2018-05-08      49.5       50.9       48.6    49.75        50.2     1298
336  2018-05-09      48.2       50.0       48.2    49.10        49.5    31228
337  2018-05-10      48.3       50.1       48.3    49.20        50.0    91332
338  2018-05-11      48.6       51.8       48.6    50.20        51.7     4145
339  2018-05-14      51.7       53.3       51.6    52.45        53.0   139864

     Srednia_por
335        49.75
336        49.10
337        49.20
338        50.20
339        52.45
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
340  2018-05-15      52.7       52.7      49.80   51.250        49.8     3097
341  2018-05-16      49.8       52.3      49.80   51.050        50.1    15986
342  2018-05-17      50.2       51.0      49.80   50.400        51.0      601
343  2018-05-18      51.7       51.9      50.00   50.950        50.4   201320
344  2018-05-21      51.9       52.2      49.55   50.875        51.7   202501

     Srednia_por
340       51.250
341       51.050
342       50.400
343       50.950
344       50.875

Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
345  2018-05-22      51.6       51.6       49.5    50.55        49.5     1153
346  2018-05-23      50.5       51.5       50.0    50.75        50.5     5380
347  2018-05-24      50.8       50.8       50.0    50.40        50.0     2677
348  2018-05-25      50.0       54.8       50.0    52.40        54.0    56145
349  2018-05-28      54.0       54.0       52.0    53.00        52.3     5896

     Srednia_por
345        50.55
346        50.75
347        50.40
348        52.40
349        53.00
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
350  2018-05-29      52.0       52.4       52.0    52.20        52.2    30563
351  2018-05-30      52.2       52.5       51.2    51.85        51.2     6243
352  2018-06-01      51.2       51.2       50.0    50.60        50.6      618
353  2018-06-04      50.3       50.6       50.3    50.45        50.3      354
354  2018-06-05      50.6       50.6       50.0    50.30        50.0    28195

     Srednia_por
350        52.20
351        51.85
352        50.60
353        50.45
354        50.30
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
355  2018-06-06     50.50      50.50      49.50   50.000       49.50     7391
356  2018-06-07     50.00      51.50      49.75   50.625       51.00   128501
357  2018-06-08     51.00      51.00      50.10   50.550       50.90      966
358  2018-06-11     49.90      49.90      48.50   49.200       49.70     2552
359  2018-06-12     49.95      49.95      49.10   49.525       49.95      552

     Srednia_por
355       50.000
356       50.625
357       50.550
358       49.200
359       49.525
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
360  2018-06-13     49.70      49.95      49.30   49.625       49.30      709
361  2018-06-14     49.05      49.20      48.70   48.950       49.00     5418
362  2018-06-15     49.60      49.60      49.00   49.300       49.00     2865
363  2018-06-18     48.65      49.00      48.65   48.825       48.80      959
364  2018-06-19     48.65      48.65      47.05   47.850       47.05    31058

     Srednia_por
360       49.625
361       48.950
362       49.300
363       48.825
364       47.850
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
365  2018-06-20     47.00       48.8      47.00   47.900       48.00    10322
366  2018-06-21     49.00       49.0      47.35   48.175       47.35    30761
367  2018-06-22     48.30       48.3      47.10   47.700       47.45     1819
368  2018-06-25     45.25       48.0      45.10   46.550       48.00    11484
369  2018-06-26     48.00       48.0      46.50   47.250       46.50    30622

     Srednia_por
365       47.900
366       48.175
367       47.700
368       46.550
369       47.250
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
370  2018-06-27     47.00      47.95       45.5   46.725       47.00    17072
371  2018-06-28     47.00      47.50       45.6   46.550       47.50     8955
372  2018-06-29     47.50      47.75       46.1   46.925       47.35    11352
373  2018-07-02     47.00      47.00       44.6   45.800       46.00     2873
374  2018-07-03     45.95      45.95       45.0   45.475       45.20    10842

     Srednia_por
370       46.725
371       46.550
372       46.925
373       45.800
374       45.475
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
375  2018-07-04      45.2       45.2      43.10   44.150       44.00    61509
376  2018-07-05      44.0       44.5      43.75   44.125       44.30     1748
377  2018-07-06      45.0       45.0      44.50   44.750       44.60    31348
378  2018-07-09      45.0       45.2      44.05   44.625       45.00   102318
379  2018-07-10      45.0       45.0      44.50   44.750       44.55      798

     Srednia_por
375       44.150
376       44.125
377       44.750
378       44.625
379       44.750
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
380  2018-07-11     44.45      44.55      42.60   43.575       42.60    53756
381  2018-07-12     42.90      43.45      42.85   43.150       42.95      725
382  2018-07-13     43.00      43.00      41.70   42.350       41.70    42951
383  2018-07-16     42.25      42.25      40.85   41.550       41.00    44344
384  2018-07-17     41.00      41.00      38.30   39.650       39.50     8425

     Srednia_por
380       43.575
381       43.150
382       42.350
383       41.550
384       39.650
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
385  2018-07-18     39.50       39.7      38.15   38.925       39.30     3614
386  2018-07-19     39.30       40.0      39.00   39.500       40.00     3117
387  2018-07-20     40.00       40.0      39.00   39.500       39.85     1838
388  2018-07-23     40.00       40.0      39.25   39.625       39.50     2266
389  2018-07-24     39.95       41.0      39.15   40.075       39.55    36570

     Srednia_por
385       38.925
386       39.500
387       39.500
388       39.625
389       40.075
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
390  2018-07-25     40.00      41.70      39.60   40.650        40.0    22879
391  2018-07-26     40.15      43.45      39.80   41.625        40.6    34156
392  2018-07-27     47.00      51.70      47.00   49.350        48.5   299514
393  2018-07-30     49.50      49.80      45.30   47.550        45.5   181262
394  2018-07-31     45.65      46.90      45.25   46.075        46.0    55189

     Srednia_por
390       40.650
391       41.625
392       49.350
393       47.550
394       46.075
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
395  2018-08-01      46.2      46.70      45.65   46.175        45.7     8503
396  2018-08-02      46.1      46.65      45.50   46.075        46.0     2107
397  2018-08-03      46.0      46.50      45.50   46.000        46.0     9027
398  2018-08-06      46.0      47.00      45.65   46.325        46.4     9574
399  2018-08-07      46.4      47.00      45.65   46.325        46.4    13162

     Srednia_por
395       46.175
396       46.075
397       46.000
398       46.325
399       46.325
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
400  2018-08-08      46.9       46.9      46.00   46.450       46.00    61973
401  2018-08-09      46.0       46.7      45.65   46.175       45.95    11832
402  2018-08-10      45.9       45.9      44.75   45.325       45.10    10585
403  2018-08-13      45.0       45.4      44.30   44.850       45.00     6892
404  2018-08-14      45.0       45.0      44.50   44.750       44.85     5162

     Srednia_por
400       46.450
401       46.175
402       45.325
403       44.850
404       44.750
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
405  2018-08-16      44.7       46.0      44.30   45.150       45.00    13468
406  2018-08-17      45.9       45.9      44.10   45.000       44.75     6364
407  2018-08-20      45.0       45.0      44.35   44.675       44.35     6753
408  2018-08-21      44.9       45.0      44.80   44.900       45.00     1152
409  2018-08-22      45.0       45.0      44.50   44.750       45.00    10774

     Srednia_por
405       45.150
406       45.000
407       44.675
408       44.900
409       44.750
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
410  2018-08-23      45.0      45.00       44.6   44.800       44.95      964
411  2018-08-24      45.0      45.00       44.8   44.900       45.00    16902
412  2018-08-27      45.0      45.00       44.7   44.850       45.00     1440
413  2018-08-28      45.0      45.05       44.8   44.925       45.00    10004
414  2018-08-29      45.0      45.00       44.6   44.800       45.00      490

     Srednia_por
410       44.800
411       44.900
412       44.850
413       44.925
414       44.800
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
415  2018-08-30     45.00      45.00      44.10   44.550       44.95     4221
416  2018-08-31     44.50      45.00      44.05   44.525       45.00     4413
417  2018-09-03     44.95      45.15      44.10   44.625       45.00    22103
418  2018-09-04     45.00      45.00      44.05   44.525       44.05      608
419  2018-09-05     44.05      44.35      43.00   43.675       44.00     1807

     Srednia_por
415       44.550
416       44.525
417       44.625
418       44.525
419       43.675
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
420  2018-09-06     44.00      44.00       41.5   42.750        41.5    58840
421  2018-09-07     41.50      43.30       41.5   42.400        43.3    72049
422  2018-09-10     44.95      44.95       42.7   43.825        43.5     2481
423  2018-09-11     43.50      44.00       42.8   43.400        43.3    23523
424  2018-09-12     43.25      43.90       43.0   43.450        43.1   115655

     Srednia_por
420       42.750
421       42.400
422       43.825
423       43.400
424       43.450
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
425  2018-09-13     43.20      43.30      43.00   43.150       43.30    11552
426  2018-09-14     42.45      42.45      39.95   41.200       42.00    29542
427  2018-09-17     42.00      43.40      42.00   42.700       43.00    11880
428  2018-09-18     43.00      46.15      43.00   44.575       46.15     4375
429  2018-09-19     46.00      46.10      44.80   45.450       44.80     2198

     Srednia_por
425       43.150
426       41.200
427       42.700
428       44.575
429       45.450
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
430  2018-09-20     46.50      46.50      42.20   44.350       45.00    17784
431  2018-09-21     45.20      45.20      43.05   44.125       43.10    18474
432  2018-09-24     44.80      44.80      43.20   44.000       43.20    27376
433  2018-09-25     43.90      43.90      43.40   43.650       43.50      137
434  2018-09-26     44.35      44.35      43.45   43.900       43.45      594

     Srednia_por
430       44.350
431       44.125
432       44.000
433       43.650
434       43.900
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
435  2018-09-27     43.25      44.25      43.25   43.750       44.10      262
436  2018-09-28     44.00      44.00      42.30   43.150       43.00     4005
437  2018-10-01     43.30      43.70      43.00   43.350       43.15    46017
438  2018-10-02     43.40      43.40      42.80   43.100       43.10      767
439  2018-10-03     42.30      43.05      42.30   42.675       42.65      107

     Srednia_por
435       43.750
436       43.150
437       43.350
438       43.100
439       42.675
Wymiary: (5, 8)

           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
440  2018-10-04     42.60       42.6      42.00   42.300       42.50      624
441  2018-10-05     42.80       42.8      42.00   42.400       42.25    22052
442  2018-10-08     42.00       42.0      40.50   41.250       40.80     4145
443  2018-10-09     40.40       40.9      38.25   39.575       38.25    23727
444  2018-10-10     38.75       39.7      37.25   38.475       37.90     6661

     Srednia_por
440       42.300
441       42.400
442       41.250
443       39.575
444       38.475
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
445  2018-10-11      37.0       37.4       35.3    36.35        36.9    52604
446  2018-10-12      37.4       38.5       36.5    37.50        37.0     2375
447  2018-10-15      36.0       38.3       35.6    36.95        38.3     7060
448  2018-10-16      37.8       38.5       37.8    38.15        38.0     4944
449  2018-10-17      38.0       40.2       38.0    39.10        40.0    10261

     Srednia_por
445        36.35
446        37.50
447        36.95
448        38.15
449        39.10
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
450  2018-10-18      40.2       40.9      39.55   40.225        40.0     8889
451  2018-10-19      40.0       40.0      37.50   38.750        37.5    48986
452  2018-10-22      38.0       38.7      37.00   37.850        37.0     3135
453  2018-10-23      37.0       37.0      35.40   36.200        35.4     2225
454  2018-10-24      35.4       35.9      34.30   35.100        34.5    45255

     Srednia_por
450       40.225
451       38.750
452       37.850
453       36.200
454       35.100
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
455  2018-10-25     34.10      34.10      31.15   32.625        33.3    47990
456  2018-10-26     33.00      33.50      32.05   32.775        32.5    21067
457  2018-10-29     32.40      32.40      24.05   28.225        24.5   273927
458  2018-10-30     25.00      26.85      24.25   25.550        25.6   167188
459  2018-10-31     25.85      25.85      25.10   25.475        25.1     9250

     Srednia_por
455       32.625
456       32.775
457       28.225
458       25.550
459       25.475
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
460  2018-11-02     25.05      25.70      25.00   25.350       25.05     9375
461  2018-11-05     25.50      25.50      24.50   25.000       25.00     3796
462  2018-11-06     25.00      25.45      23.95   24.700       23.95   316266
463  2018-11-07     24.30      24.30      23.45   23.875       23.50    11283
464  2018-11-08     23.40      23.85      23.20   23.525       23.55     2584

     Srednia_por
460       25.350
461       25.000
462       24.700
463       23.875
464       23.525
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
465  2018-11-09      23.7      23.70      22.70   23.200        23.0    16333
466  2018-11-13      22.7      22.70      21.25   21.975        22.0   107495
467  2018-11-14      22.0      22.90      22.00   22.450        22.9     2385
468  2018-11-15      22.5      24.40      22.40   23.400        22.9    38548
469  2018-11-16      22.9      23.05      21.30   22.175        21.5    24828

     Srednia_por
465       23.200
466       21.975
467       22.450
468       23.400
469       22.175
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
470  2018-11-19     20.70      22.00      20.55   21.275       21.90   129388
471  2018-11-20     21.20      21.65      20.55   21.100       20.60    13173
472  2018-11-21     20.55      21.00      20.30   20.650       21.00    12929
473  2018-11-22     21.00      21.00      19.50   20.250       20.55    13781
474  2018-11-23     20.70      21.00      20.70   20.850       21.00    26154

     Srednia_por
470       21.275
471       21.100
472       20.650
473       20.250
474       20.850
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
475  2018-11-26     21.00      21.50      20.20    20.85       20.80    42155
476  2018-11-27     21.50      21.50      19.62    20.56       20.70    77268
477  2018-11-28     20.50      22.05      20.05    21.05       20.35   250151
478  2018-11-29     20.65      21.60      20.50    21.05       21.00    13779
479  2018-11-30     21.00      21.65      20.35    21.00       20.70    13647

     Srednia_por
475        20.85
476        20.56
477        21.05
478        21.05
479        21.00
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
480  2018-12-03     21.00      21.70      20.55   21.125       21.70    68783
481  2018-12-04     22.00      23.20      21.35   22.275       22.50   353461
482  2018-12-05     21.95      24.45      21.75   23.100       23.95    51980
483  2018-12-06     23.90      24.70      22.80   23.750       24.05    43293
484  2018-12-07     24.25      26.15      24.25   25.200       25.00    67506

     Srednia_por
480       21.125
481       22.275
482       23.100
483       23.750
484       25.200
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
485  2018-12-10     24.85      25.45      23.80   24.625       23.80    16557
486  2018-12-11     24.10      25.60      24.05   24.825       24.60    19043
487  2018-12-12     25.50      25.50      24.40   24.950       24.80     9005
488  2018-12-13     25.40      25.40      24.40   24.900       24.45    12834
489  2018-12-14     24.70      24.70      23.05   23.875       23.10    16592

     Srednia_por
485       24.625
486       24.825
487       24.950
488       24.900
489       23.875
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
490  2018-12-17     22.90       23.8      22.25   23.025       22.60    13764
491  2018-12-18     22.50       22.7      21.80   22.250       22.10    23802
492  2018-12-19     21.90       22.7      21.90   22.300       22.45    71883
493  2018-12-20     22.45       23.1      22.45   22.775       22.65    41918
494  2018-12-21     22.45       22.7      22.45   22.575       22.50    24989

     Srednia_por
490       23.025
491       22.250
492       22.300
493       22.775
494       22.575
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
495  2018-12-27     22.90      22.90      22.30   22.600       22.50     3055
496  2018-12-28     22.45      22.85      22.45   22.650       22.75     5059
497  2019-01-02     22.75      24.30      22.75   23.525       23.95    12478
498  2019-01-03     23.80      24.45      23.05   23.750       23.05     8608
499  2019-01-04     23.05      23.55      23.05   23.300       23.45     2021

     Srednia_por
495       22.600
496       22.650
497       23.525
498       23.750
499       23.300
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
500  2019-01-07     23.50      23.75       22.7   23.225        22.7     7736
501  2019-01-08     22.75      22.90       22.4   22.650        22.4     9846
502  2019-01-09     22.50      22.75       22.3   22.525        22.5     7142
503  2019-01-10     22.70      23.00       22.4   22.700        22.6    17776
504  2019-01-11     22.85      22.95       22.5   22.725        22.5     9576

     Srednia_por
500       23.225
501       22.650
502       22.525
503       22.700
504       22.725
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
505  2019-01-14     22.75      22.75      22.50   22.625       22.55     3058
506  2019-01-15     22.55      22.85      21.90   22.375       22.00    19106
507  2019-01-16     22.00      22.50      21.25   21.875       22.40    11917
508  2019-01-17     22.40      22.70      22.20   22.450       22.60     5746
509  2019-01-18     22.70      22.75      22.40   22.575       22.60    33823

     Srednia_por
505       22.625
506       22.375
507       21.875
508       22.450
509       22.575
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
510  2019-01-21     22.70      23.35      22.55   22.950       23.35    24382
511  2019-01-22     23.50      24.45      23.50   23.975       24.25    16241
512  2019-01-23     24.25      24.80      24.00   24.400       24.80     6362
513  2019-01-24     24.90      25.00      24.00   24.500       24.35     6868
514  2019-01-25     24.35      24.40      23.60   24.000       24.10     8815

     Srednia_por
510       22.950
511       23.975
512       24.400
513       24.500
514       24.000
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
515  2019-01-28     24.10      24.40      23.90   24.150       24.05     4685
516  2019-01-29     24.00      24.00      23.00   23.500       23.55    72542
517  2019-01-30     23.85      23.85      23.35   23.600       23.50    29746
518  2019-01-31     23.55      23.90      23.35   23.625       23.90    16931
519  2019-02-01     23.90      24.10      23.90   24.000       23.95    29077

     Srednia_por
515       24.150
516       23.500
517       23.600
518       23.625
519       24.000
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
520  2019-02-04      24.2      25.30      24.20   24.750       25.20     8615
521  2019-02-05      25.4      26.70      25.40   26.050       26.15    32601
522  2019-02-06      26.3      26.35      25.60   25.975       25.60    12218
523  2019-02-07      25.9      25.90      25.20   25.550       25.50     4661
524  2019-02-08      25.4      26.30      25.05   25.675       26.30     8003

     Srednia_por
520       24.750
521       26.050
522       25.975
523       25.550
524       25.675
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
525  2019-02-11     26.00      26.20      25.75   25.975       25.90    13667
526  2019-02-12     25.90      26.00      24.40   25.200       24.95    22223
527  2019-02-13     25.10      25.10      23.80   24.450       24.00    13796
528  2019-02-14     23.85      24.50      23.85   24.175       24.00    55679
529  2019-02-15     24.40      24.85      24.00   24.425       24.70    11279

     Srednia_por
525       25.975
526       25.200
527       24.450
528       24.175
529       24.425
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
530  2019-02-18     24.80      24.80      24.00   24.400       24.65     3902
531  2019-02-19     24.45      24.45      23.85   24.150       24.10     3909
532  2019-02-20     23.90      24.10      23.35   23.725       23.50    13195
533  2019-02-21     23.45      24.00      23.45   23.725       23.95     4439
534  2019-02-22     23.90      24.20      23.55   23.875       24.10     4000

     Srednia_por
530       24.400
531       24.150
532       23.725
533       23.725
534       23.875
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
535  2019-02-25     24.10      25.00      23.90   24.450       24.85    15977
536  2019-02-26     24.95      25.80      24.90   25.350       25.35    29626
537  2019-02-27     25.80      26.25      25.00   25.625       25.00    15033
538  2019-02-28     25.30      25.30      24.55   24.925       24.80     7211
539  2019-03-01     25.10      25.30      24.80   25.050       24.80     2635

     Srednia_por
535       24.450
536       25.350
537       25.625
538       24.925
539       25.050

Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
540  2019-03-04     24.85      25.40      24.60   25.000       24.60     6639
541  2019-03-05     24.60      24.80      24.15   24.475       24.50     4650
542  2019-03-06     24.65      24.65      24.20   24.425       24.50     1512
543  2019-03-07     24.70      24.70      24.25   24.475       24.35     1431
544  2019-03-08     24.20      24.20      23.80   24.000       24.00     6500

     Srednia_por
540       25.000
541       24.475
542       24.425
543       24.475
544       24.000
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
545  2019-03-11     24.00      24.80       22.2   23.500       22.40    37754
546  2019-03-12     22.30      22.35       21.1   21.725       22.25    98805
547  2019-03-13     22.35      22.50       22.0   22.250       22.50     9966
548  2019-03-14     22.80      23.35       22.7   23.025       23.00    48817
549  2019-03-15     23.00      24.35       23.0   23.675       24.35    51347

     Srednia_por
545       23.500
546       21.725
547       22.250
548       23.025
549       23.675
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
550  2019-03-18     24.35      24.45      23.50   23.975       24.40    12905
551  2019-03-19     24.45      25.50      24.45   24.975       24.75    25108
552  2019-03-20     24.70      26.85      24.70   25.775       26.85    25715
553  2019-03-21     26.80      29.45      26.80   28.125       28.05    81211
554  2019-03-22     28.10      28.75      27.00   27.875       27.35    24205

     Srednia_por
550       23.975
551       24.975
552       25.775
553       28.125
554       27.875
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
555  2019-03-25     27.10      27.15      26.45    26.80        26.7    10696
556  2019-03-26     27.00      28.30      27.00    27.65        28.0    14766
557  2019-03-27     28.15      28.50      26.60    27.55        26.6    18022
558  2019-03-28     26.60      26.70      25.00    25.85        26.1    44429
559  2019-03-29     26.35      26.35      25.25    25.80        25.9    11652

     Srednia_por
555        26.80
556        27.65
557        27.55
558        25.85
559        25.80
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
560  2019-04-01     26.15      27.00      26.05   26.525       26.40    14774
561  2019-04-02     27.00      28.50      27.00   27.750       27.95    17724
562  2019-04-03     28.60      29.50      28.40   28.950       29.40    42813
563  2019-04-04     29.50      30.95      29.30   30.125       29.30    54442
564  2019-04-05     29.30      30.45      28.20   29.325       28.60    45406

     Srednia_por
560       26.525
561       27.750
562       28.950
563       30.125
564       29.325
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
565  2019-04-08     28.55      29.40       28.1   28.750       28.85     8171
566  2019-04-09     29.20      30.20       29.0   29.600       29.20    18135
567  2019-04-10     29.65      29.75       28.8   29.275       29.05     7375
568  2019-04-11     29.20      29.30       28.8   29.050       29.30     4317
569  2019-04-12     29.15      29.30       28.5   28.900       28.85    99781

     Srednia_por
565       28.750
566       29.600
567       29.275
568       29.050
569       28.900
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
570  2019-04-15     28.85      29.15      28.55   28.850       29.10     1932
571  2019-04-16     29.10      29.20      27.95   28.575       28.65     8167
572  2019-04-17     28.65      29.20      28.40   28.800       28.40     4118
573  2019-04-18     28.15      28.70      28.15   28.425       28.40     4199
574  2019-04-23     28.40      28.60      26.35   27.475       27.80    27439

     Srednia_por
570       28.850
571       28.575
572       28.800
573       28.425
574       27.475
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
575  2019-04-24     29.00      29.80      28.60   29.200       29.35    32943
576  2019-04-25     29.20      29.20      28.55   28.875       28.80    52923
577  2019-04-26     29.00      29.20      28.30   28.750       28.35     6838
578  2019-04-29     28.40      28.40      27.30   27.850       28.05     8187
579  2019-04-30     28.05      28.05      27.50   27.775       27.60    10398

     Srednia_por
575       29.200
576       28.875
577       28.750
578       27.850
579       27.775
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
580  2019-05-02     27.35      27.55      27.20   27.375       27.35    14970
581  2019-05-06     27.10      27.50      26.40   26.950       26.70    18797
582  2019-05-07     27.10      27.40      26.85   27.125       26.90    23246
583  2019-05-08     26.75      28.00      26.75   27.375       28.00    27073
584  2019-05-09     27.60      29.05      27.60   28.325       28.25    30500

     Srednia_por
580       27.375
581       26.950
582       27.125
583       27.375
584       28.325
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
585  2019-05-10     28.25      28.35      27.65   28.000       27.90    23207
586  2019-05-13     27.90      27.90      27.15   27.525       27.15     7771
587  2019-05-14     27.10      27.95      27.10   27.525       27.70     5835
588  2019-05-15     28.00      28.50      27.40   27.950       28.20    10134
589  2019-05-16     27.95      28.50      27.20   27.850       28.50    26746

     Srednia_por
585       28.000
586       27.525
587       27.525
588       27.950
589       27.850
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
590  2019-05-17     28.50      28.60      28.00   28.300       28.50     7071
591  2019-05-20     27.95      28.60      27.95   28.275       28.20     1359
592  2019-05-21     27.90      28.55      27.70   28.125       28.55     7354
593  2019-05-22     28.40      28.75      28.25   28.500       28.60     3383
594  2019-05-23     28.85      29.90      28.85   29.375       29.15    16602

     Srednia_por
590       28.300
591       28.275
592       28.125
593       28.500
594       29.375
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
595  2019-05-24     29.75       30.0      29.15   29.575       29.65    22503
596  2019-05-27     29.65       30.8      29.65   30.225       30.70    21936
597  2019-05-28     31.00       31.8      30.90   31.350       31.50    10665
598  2019-05-29     32.00       32.0      30.40   31.200       30.60     8034
599  2019-05-30     30.65       30.9      30.20   30.550       30.25    35480

     Srednia_por
595       29.575
596       30.225
597       31.350
598       31.200
599       30.550
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
600  2019-05-31     30.15      30.15      28.75   29.450       29.75    22738
601  2019-06-03     29.80      30.40      29.80   30.100       30.00    11295
602  2019-06-04     30.10      30.10      29.00   29.550       29.50     7612
603  2019-06-05     29.50      29.75      28.70   29.225       29.75     5461
604  2019-06-06     29.75      30.40      29.50   29.950       29.80     7343

     Srednia_por
600       29.450
601       30.100
602       29.550
603       29.225
604       29.950
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
605  2019-06-07     29.75      30.30      29.50   29.900       29.50     4622
606  2019-06-10     29.50      29.80      29.15   29.475       29.45     4549
607  2019-06-11     30.00      30.00      29.35   29.675       29.75     4571
608  2019-06-12     29.75      30.15      29.75   29.950       29.95     2807
609  2019-06-13     30.60      31.00      29.75   30.375       29.75    12030

     Srednia_por
605       29.900
606       29.475
607       29.675
608       29.950
609       30.375
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
610  2019-06-14      29.8      30.45      29.70   30.075        29.9     7286
611  2019-06-17      29.9      30.10      29.90   30.000        29.9    91994
612  2019-06-18      30.6      30.60      30.00   30.300        30.6     9745
613  2019-06-19      30.5      31.00      30.50   30.750        30.7     3053
614  2019-06-21      31.0      31.10      29.25   30.175        30.1    11413

     Srednia_por
610       30.075
611       30.000
612       30.300
613       30.750
614       30.175
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
615  2019-06-24      30.4      30.40      30.10   30.250       30.10     2824
616  2019-06-25      30.4      30.40      29.60   30.000       30.00     3967
617  2019-06-26      30.0      30.00      29.65   29.825       29.90     2256
618  2019-06-27      29.9      29.95      29.90   29.925       29.95     3585
619  2019-06-28      30.0      30.00      29.65   29.825       29.90     3733

     Srednia_por
615       30.250
616       30.000
617       29.825
618       29.925
619       29.825
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
620  2019-07-01     29.90      30.55      29.65   30.100       30.55    12622
621  2019-07-02     30.60      30.60      30.20   30.400       30.50      848
622  2019-07-03     30.95      30.95      30.50   30.725       30.90     8389
623  2019-07-04     30.95      32.00      30.65   31.325       31.85     9875
624  2019-07-05     32.00      33.45      32.00   32.725       32.00    11295

     Srednia_por
620       30.100
621       30.400
622       30.725
623       31.325
624       32.725
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
625  2019-07-08     33.25      33.25      31.80   32.525       31.95    14768
626  2019-07-09     32.00      32.85      30.90   31.875       31.20   108514
627  2019-07-10     31.20      31.65      30.50   31.075       31.15   110320
628  2019-07-11     31.00      32.80      30.85   31.825       32.80     6762
629  2019-07-12     32.40      32.70      31.65   32.175       31.90    18057

     Srednia_por
625       32.525
626       31.875
627       31.075
628       31.825
629       32.175
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
630  2019-07-15     32.30      32.70      32.30   32.500       32.50     1186
631  2019-07-16     32.50      32.60      32.00   32.300       32.05     1527
632  2019-07-17     32.00      32.45      31.65   32.050       31.65     2443
633  2019-07-18     31.65      32.00      31.45   31.725       32.00      737
634  2019-07-19     32.55      32.70      32.20   32.450       32.60     4313

     Srednia_por
630       32.500
631       32.300
632       32.050
633       31.725
634       32.450
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
635  2019-07-22     32.80      33.35      32.50   32.925       32.90    32398
636  2019-07-23     33.00      33.00      32.50   32.750       32.75     2417
637  2019-07-24     32.90      32.90      32.00   32.450       32.00     3183
638  2019-07-25     29.95      29.95      27.00   28.475       28.00    81981
639  2019-07-26     28.00      28.00      24.35   26.175       24.85    73517

     Srednia_por
635       32.925
636       32.750
637       32.450
638       28.475
639       26.175

Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
640  2019-07-29      24.0      25.50       24.0   24.750       25.00    17702
641  2019-07-30      25.1      25.65       25.1   25.375       25.50     2894
642  2019-07-31      27.0      27.00       25.8   26.400       26.50    17437
643  2019-08-01      26.5      27.15       25.8   26.475       26.10    11183
644  2019-08-02      26.2      26.90       25.9   26.400       26.55     3613

     Srednia_por
640       24.750
641       25.375
642       26.400
643       26.475
644       26.400
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
645  2019-08-05      26.6      26.60       25.8   26.200       25.80     3735
646  2019-08-06      25.8      26.50       25.8   26.150       26.05     4862
647  2019-08-07      25.9      26.95       25.9   26.425       26.10     4649
648  2019-08-08      26.4      26.45       25.9   26.175       26.00     5688
649  2019-08-09      26.0      26.50       26.0   26.250       26.50     3341

     Srednia_por
645       26.200
646       26.150
647       26.425
648       26.175
649       26.250
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
650  2019-08-12     26.10      26.15       25.7   25.925       25.95     1552
651  2019-08-13     25.10      25.60       24.2   24.900       25.40    11934
652  2019-08-14     25.55      25.55       24.9   25.225       25.20   134730
653  2019-08-16     25.20      25.30       24.8   25.050       25.00     4209
654  2019-08-19     24.65      25.25       24.6   24.925       25.20     3564

     Srednia_por
650       25.925
651       24.900
652       25.225
653       25.050
654       24.925
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
655  2019-08-20      25.0      25.20      24.35   24.775       24.90     2832
656  2019-08-21      24.2      25.10      24.20   24.650       24.80     1281
657  2019-08-22      24.8      25.65      24.70   25.175       25.00     4882
658  2019-08-23      25.3      25.30      24.55   24.925       24.85     6334
659  2019-08-26      24.1      25.45      24.10   24.775       25.00    13126

     Srednia_por
655       24.775
656       24.650
657       25.175
658       24.925
659       24.775
Wymiary: (5, 8)
           Data  Otwarcie  Najwyzszy  Najnizszy  Srednia  Zamkniecie  Wolumen  \
660  2019-08-27     25.00      25.20       24.5   24.850       24.95     8037
661  2019-08-28     25.20      25.20       24.3   24.750       24.30     1345
662  2019-08-29     25.00      25.00       24.2   24.600       25.00      977
663  2019-08-30     24.95      25.00       24.4   24.700       25.00     3335
664  2019-09-02     25.00      25.15       24.7   24.925       25.00      589

     Srednia_por
660       24.850
661       24.750
662       24.600
663       24.700
664       24.925